2024-02-08 16:28:31,382 - kedro.framework.session.session - INFO - Kedro project tentative_agri_proj
2024-02-08 16:28:37,382 - tensorflow - WARNING - From C:\Users\paolo\Documents\GitHub\tentative_agri_proj\.venv\Lib\site-packages\keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

2024-02-08 16:28:37,775 - py.warnings - WARNING - C:\Users\paolo\Documents\GitHub\tentative_agri_proj\.venv\Lib\site-packages\kedro\framework\project\__init__.py:366: UserWarning: An error occurred while importing the 'tentative_agri_proj.pipelines.model_training_eval' module. Nothing defined therein will be returned by 'find_pipelines'.

Traceback (most recent call last):
  File "C:\Users\paolo\Documents\GitHub\tentative_agri_proj\.venv\Lib\site-packages\kedro\framework\project\__init__.py", line 364, in find_pipelines
    pipeline_module = importlib.import_module(pipeline_module_name)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\paolo\AppData\Local\Programs\Python\Python311\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\paolo\Documents\GitHub\tentative_agri_proj\src\tentative_agri_proj\pipelines\model_training_eval\__init__.py", line 1, in <module>
    from .pipeline import create_pipeline  # NOQA
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\paolo\Documents\GitHub\tentative_agri_proj\src\tentative_agri_proj\pipelines\model_training_eval\pipeline.py", line 2, in <module>
    from .nodes import windowing, train_model, evaluate_model, save_model
  File "C:\Users\paolo\Documents\GitHub\tentative_agri_proj\src\tentative_agri_proj\pipelines\model_training_eval\nodes.py", line 5, in <module>
    from ..model_definition import MyTFModel
ImportError: cannot import name 'MyTFModel' from 'tentative_agri_proj.pipelines.model_definition' (C:\Users\paolo\Documents\GitHub\tentative_agri_proj\src\tentative_agri_proj\pipelines\model_definition\__init__.py)

  warnings.warn(

2024-02-08 16:35:27,646 - kedro.framework.session.session - INFO - Kedro project tentative_agri_proj
2024-02-08 16:35:33,581 - tensorflow - WARNING - From C:\Users\paolo\Documents\GitHub\tentative_agri_proj\.venv\Lib\site-packages\keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

2024-02-08 16:35:34,018 - py.warnings - WARNING - C:\Users\paolo\Documents\GitHub\tentative_agri_proj\.venv\Lib\site-packages\kedro\framework\project\__init__.py:366: UserWarning: An error occurred while importing the 'tentative_agri_proj.pipelines.model_training_eval' module. Nothing defined therein will be returned by 'find_pipelines'.

Traceback (most recent call last):
  File "C:\Users\paolo\Documents\GitHub\tentative_agri_proj\.venv\Lib\site-packages\kedro\framework\project\__init__.py", line 364, in find_pipelines
    pipeline_module = importlib.import_module(pipeline_module_name)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\paolo\AppData\Local\Programs\Python\Python311\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\paolo\Documents\GitHub\tentative_agri_proj\src\tentative_agri_proj\pipelines\model_training_eval\__init__.py", line 1, in <module>
    from .pipeline import create_pipeline  # NOQA
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\paolo\Documents\GitHub\tentative_agri_proj\src\tentative_agri_proj\pipelines\model_training_eval\pipeline.py", line 2, in <module>
    from .nodes import windowing, train_model, evaluate_model, save_model
  File "C:\Users\paolo\Documents\GitHub\tentative_agri_proj\src\tentative_agri_proj\pipelines\model_training_eval\nodes.py", line 5, in <module>
    from ..model_definition import MyTFModel
ImportError: cannot import name 'MyTFModel' from 'tentative_agri_proj.pipelines.model_definition' (C:\Users\paolo\Documents\GitHub\tentative_agri_proj\src\tentative_agri_proj\pipelines\model_definition\__init__.py)

  warnings.warn(

2024-02-08 16:37:26,223 - kedro.framework.session.session - INFO - Kedro project tentative_agri_proj
2024-02-08 16:37:31,499 - tensorflow - WARNING - From C:\Users\paolo\Documents\GitHub\tentative_agri_proj\.venv\Lib\site-packages\keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

2024-02-08 16:37:31,855 - py.warnings - WARNING - C:\Users\paolo\Documents\GitHub\tentative_agri_proj\.venv\Lib\site-packages\kedro\framework\project\__init__.py:366: UserWarning: An error occurred while importing the 'tentative_agri_proj.pipelines.model_training_eval' module. Nothing defined therein will be returned by 'find_pipelines'.

Traceback (most recent call last):
  File "C:\Users\paolo\Documents\GitHub\tentative_agri_proj\.venv\Lib\site-packages\kedro\framework\project\__init__.py", line 364, in find_pipelines
    pipeline_module = importlib.import_module(pipeline_module_name)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\paolo\AppData\Local\Programs\Python\Python311\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\paolo\Documents\GitHub\tentative_agri_proj\src\tentative_agri_proj\pipelines\model_training_eval\__init__.py", line 1, in <module>
    from .pipeline import create_pipeline  # NOQA
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\paolo\Documents\GitHub\tentative_agri_proj\src\tentative_agri_proj\pipelines\model_training_eval\pipeline.py", line 2, in <module>
    from .nodes import windowing, train_model, evaluate_model, save_model
  File "C:\Users\paolo\Documents\GitHub\tentative_agri_proj\src\tentative_agri_proj\pipelines\model_training_eval\nodes.py", line 5, in <module>
    from ..model_definition import MyTFModel
ImportError: cannot import name 'MyTFModel' from 'tentative_agri_proj.pipelines.model_definition' (C:\Users\paolo\Documents\GitHub\tentative_agri_proj\src\tentative_agri_proj\pipelines\model_definition\__init__.py)

  warnings.warn(

2024-02-08 16:37:46,696 - kedro.framework.session.session - INFO - Kedro project tentative_agri_proj
2024-02-08 16:37:51,741 - tensorflow - WARNING - From C:\Users\paolo\Documents\GitHub\tentative_agri_proj\.venv\Lib\site-packages\keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

2024-02-08 16:37:52,110 - py.warnings - WARNING - C:\Users\paolo\Documents\GitHub\tentative_agri_proj\.venv\Lib\site-packages\kedro\framework\project\__init__.py:366: UserWarning: An error occurred while importing the 'tentative_agri_proj.pipelines.model_training_eval' module. Nothing defined therein will be returned by 'find_pipelines'.

Traceback (most recent call last):
  File "C:\Users\paolo\Documents\GitHub\tentative_agri_proj\.venv\Lib\site-packages\kedro\framework\project\__init__.py", line 364, in find_pipelines
    pipeline_module = importlib.import_module(pipeline_module_name)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\paolo\AppData\Local\Programs\Python\Python311\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\paolo\Documents\GitHub\tentative_agri_proj\src\tentative_agri_proj\pipelines\model_training_eval\__init__.py", line 1, in <module>
    from .pipeline import create_pipeline  # NOQA
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\paolo\Documents\GitHub\tentative_agri_proj\src\tentative_agri_proj\pipelines\model_training_eval\pipeline.py", line 2, in <module>
    from .nodes import windowing, train_model, evaluate_model, save_model
  File "C:\Users\paolo\Documents\GitHub\tentative_agri_proj\src\tentative_agri_proj\pipelines\model_training_eval\nodes.py", line 5, in <module>
    from ..model_definition import MyTFModel
ImportError: cannot import name 'MyTFModel' from 'tentative_agri_proj.pipelines.model_definition' (C:\Users\paolo\Documents\GitHub\tentative_agri_proj\src\tentative_agri_proj\pipelines\model_definition\__init__.py)

  warnings.warn(

2024-02-08 16:37:52,222 - kedro.io.data_catalog - INFO - Loading data from 'logger_3_betula' (CSVDataSet)...
2024-02-08 16:37:52,449 - kedro.pipeline.node - INFO - Running node: data_cleaning_node: data_cleaning([logger_3_betula]) -> [logger_3_betula_cleaned]
2024-02-08 16:37:52,582 - kedro.pipeline.node - ERROR - Node 'data_cleaning_node: data_cleaning([logger_3_betula]) -> [logger_3_betula_cleaned]' failed with error: 
Failed to save outputs of node data_cleaning_node: data_cleaning([logger_3_betula]) -> [logger_3_betula_cleaned].
The node definition contains a list of outputs ['logger_3_betula_cleaned'], whereas the node function returned a 'DataFrame'.
2024-02-08 16:37:52,607 - kedro.runner.sequential_runner - WARNING - No nodes ran. Repeat the previous command to attempt a new run.
2024-02-08 16:38:44,268 - kedro.framework.session.session - INFO - Kedro project tentative_agri_proj
2024-02-08 16:38:49,525 - tensorflow - WARNING - From C:\Users\paolo\Documents\GitHub\tentative_agri_proj\.venv\Lib\site-packages\keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

2024-02-08 16:38:49,878 - py.warnings - WARNING - C:\Users\paolo\Documents\GitHub\tentative_agri_proj\.venv\Lib\site-packages\kedro\framework\project\__init__.py:366: UserWarning: An error occurred while importing the 'tentative_agri_proj.pipelines.model_training_eval' module. Nothing defined therein will be returned by 'find_pipelines'.

Traceback (most recent call last):
  File "C:\Users\paolo\Documents\GitHub\tentative_agri_proj\.venv\Lib\site-packages\kedro\framework\project\__init__.py", line 364, in find_pipelines
    pipeline_module = importlib.import_module(pipeline_module_name)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\paolo\AppData\Local\Programs\Python\Python311\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\paolo\Documents\GitHub\tentative_agri_proj\src\tentative_agri_proj\pipelines\model_training_eval\__init__.py", line 1, in <module>
    from .pipeline import create_pipeline  # NOQA
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\paolo\Documents\GitHub\tentative_agri_proj\src\tentative_agri_proj\pipelines\model_training_eval\pipeline.py", line 2, in <module>
    from .nodes import windowing, train_model, evaluate_model, save_model
  File "C:\Users\paolo\Documents\GitHub\tentative_agri_proj\src\tentative_agri_proj\pipelines\model_training_eval\nodes.py", line 5, in <module>
    from ..model_definition import MyTFModel
ImportError: cannot import name 'MyTFModel' from 'tentative_agri_proj.pipelines.model_definition' (C:\Users\paolo\Documents\GitHub\tentative_agri_proj\src\tentative_agri_proj\pipelines\model_definition\__init__.py)

  warnings.warn(

2024-02-08 16:38:49,980 - kedro.io.data_catalog - INFO - Loading data from 'logger_3_betula' (CSVDataSet)...
2024-02-08 16:38:50,141 - kedro.pipeline.node - INFO - Running node: data_cleaning_node: data_cleaning([logger_3_betula]) -> [logger_3_betula_cleaned]
2024-02-08 16:38:50,260 - kedro.io.data_catalog - INFO - Saving data to 'logger_3_betula_cleaned' (MemoryDataset)...
2024-02-08 16:38:50,278 - kedro.runner.sequential_runner - INFO - Completed 1 out of 4 tasks
2024-02-08 16:38:50,278 - kedro.pipeline.node - INFO - Running node: define_model_node: define_model(None) -> [model]
2024-02-08 16:38:50,636 - tensorflow - WARNING - From C:\Users\paolo\Documents\GitHub\tentative_agri_proj\.venv\Lib\site-packages\keras\src\utils\tf_utils.py:585: The name tf.executing_eagerly_outside_functions is deprecated. Please use tf.compat.v1.executing_eagerly_outside_functions instead.

2024-02-08 16:38:50,786 - kedro.pipeline.node - ERROR - Node 'define_model_node: define_model(None) -> [model]' failed with error: 
Failed to save outputs of node define_model_node: define_model(None) -> [model].
The node definition contains a list of outputs ['model'], whereas the node function returned a 'MyTFModel'.
2024-02-08 16:38:50,786 - kedro.runner.sequential_runner - WARNING - There are 3 nodes that have not run.
You can resume the pipeline run from the nearest nodes with persisted inputs by adding the following argument to your previous command:
  --from-nodes "data_cleaning_node"
2024-02-08 16:39:18,442 - kedro.framework.session.session - INFO - Kedro project tentative_agri_proj
2024-02-08 16:39:23,613 - tensorflow - WARNING - From C:\Users\paolo\Documents\GitHub\tentative_agri_proj\.venv\Lib\site-packages\keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

2024-02-08 16:39:24,000 - py.warnings - WARNING - C:\Users\paolo\Documents\GitHub\tentative_agri_proj\.venv\Lib\site-packages\kedro\framework\project\__init__.py:366: UserWarning: An error occurred while importing the 'tentative_agri_proj.pipelines.model_training_eval' module. Nothing defined therein will be returned by 'find_pipelines'.

Traceback (most recent call last):
  File "C:\Users\paolo\Documents\GitHub\tentative_agri_proj\.venv\Lib\site-packages\kedro\framework\project\__init__.py", line 364, in find_pipelines
    pipeline_module = importlib.import_module(pipeline_module_name)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\paolo\AppData\Local\Programs\Python\Python311\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\paolo\Documents\GitHub\tentative_agri_proj\src\tentative_agri_proj\pipelines\model_training_eval\__init__.py", line 1, in <module>
    from .pipeline import create_pipeline  # NOQA
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\paolo\Documents\GitHub\tentative_agri_proj\src\tentative_agri_proj\pipelines\model_training_eval\pipeline.py", line 2, in <module>
    from .nodes import windowing, train_model, evaluate_model, save_model
  File "C:\Users\paolo\Documents\GitHub\tentative_agri_proj\src\tentative_agri_proj\pipelines\model_training_eval\nodes.py", line 5, in <module>
    from ..model_definition import MyTFModel
ImportError: cannot import name 'MyTFModel' from 'tentative_agri_proj.pipelines.model_definition' (C:\Users\paolo\Documents\GitHub\tentative_agri_proj\src\tentative_agri_proj\pipelines\model_definition\__init__.py)

  warnings.warn(

2024-02-08 16:39:24,097 - kedro.io.data_catalog - INFO - Loading data from 'logger_3_betula' (CSVDataSet)...
2024-02-08 16:39:24,261 - kedro.pipeline.node - INFO - Running node: data_cleaning_node: data_cleaning([logger_3_betula]) -> [logger_3_betula_cleaned]
2024-02-08 16:39:24,395 - kedro.io.data_catalog - INFO - Saving data to 'logger_3_betula_cleaned' (MemoryDataset)...
2024-02-08 16:39:24,413 - kedro.runner.sequential_runner - INFO - Completed 1 out of 4 tasks
2024-02-08 16:39:24,413 - kedro.pipeline.node - INFO - Running node: define_model_node: define_model(None) -> [model]
2024-02-08 16:39:24,595 - tensorflow - WARNING - From C:\Users\paolo\Documents\GitHub\tentative_agri_proj\.venv\Lib\site-packages\keras\src\utils\tf_utils.py:585: The name tf.executing_eagerly_outside_functions is deprecated. Please use tf.compat.v1.executing_eagerly_outside_functions instead.

2024-02-08 16:39:24,729 - kedro.io.data_catalog - INFO - Saving data to 'model' (MemoryDataset)...
2024-02-08 16:39:24,744 - kedro.runner.sequential_runner - WARNING - There are 3 nodes that have not run.
You can resume the pipeline run from the nearest nodes with persisted inputs by adding the following argument to your previous command:
  --from-nodes "data_cleaning_node"
2024-02-08 16:44:10,874 - kedro.framework.session.session - INFO - Kedro project tentative_agri_proj
2024-02-08 16:44:16,561 - tensorflow - WARNING - From C:\Users\paolo\Documents\GitHub\tentative_agri_proj\.venv\Lib\site-packages\keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

2024-02-08 16:44:17,000 - py.warnings - WARNING - C:\Users\paolo\Documents\GitHub\tentative_agri_proj\.venv\Lib\site-packages\kedro\framework\project\__init__.py:366: UserWarning: An error occurred while importing the 'tentative_agri_proj.pipelines.agri_pipeline' module. Nothing defined therein will be returned by 'find_pipelines'.

Traceback (most recent call last):
  File "C:\Users\paolo\Documents\GitHub\tentative_agri_proj\.venv\Lib\site-packages\kedro\framework\project\__init__.py", line 364, in find_pipelines
    pipeline_module = importlib.import_module(pipeline_module_name)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\paolo\AppData\Local\Programs\Python\Python311\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\paolo\Documents\GitHub\tentative_agri_proj\src\tentative_agri_proj\pipelines\agri_pipeline\__init__.py", line 1, in <module>
    from .pipeline import create_pipeline  # NOQA
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\paolo\Documents\GitHub\tentative_agri_proj\src\tentative_agri_proj\pipelines\agri_pipeline\pipeline.py", line 2, in <module>
    from .nodes import data_cleaning, split_data, normalise_data, define_model, windowing, train_model, evaluate_model, save_model
  File "C:\Users\paolo\Documents\GitHub\tentative_agri_proj\src\tentative_agri_proj\pipelines\agri_pipeline\nodes.py", line 90, in <module>
    from ..model_definition import MyTFModel
ModuleNotFoundError: No module named 'tentative_agri_proj.pipelines.model_definition'

  warnings.warn(

2024-02-08 16:45:01,267 - kedro.framework.session.session - INFO - Kedro project tentative_agri_proj
2024-02-08 16:45:06,688 - tensorflow - WARNING - From C:\Users\paolo\Documents\GitHub\tentative_agri_proj\.venv\Lib\site-packages\keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

2024-02-08 16:45:07,056 - py.warnings - WARNING - C:\Users\paolo\Documents\GitHub\tentative_agri_proj\.venv\Lib\site-packages\kedro\framework\project\__init__.py:366: UserWarning: An error occurred while importing the 'tentative_agri_proj.pipelines.agri_pipeline' module. Nothing defined therein will be returned by 'find_pipelines'.

Traceback (most recent call last):
  File "C:\Users\paolo\Documents\GitHub\tentative_agri_proj\.venv\Lib\site-packages\kedro\framework\project\__init__.py", line 364, in find_pipelines
    pipeline_module = importlib.import_module(pipeline_module_name)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\paolo\AppData\Local\Programs\Python\Python311\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\paolo\Documents\GitHub\tentative_agri_proj\src\tentative_agri_proj\pipelines\agri_pipeline\__init__.py", line 1, in <module>
    from .pipeline import create_pipeline  # NOQA
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\paolo\Documents\GitHub\tentative_agri_proj\src\tentative_agri_proj\pipelines\agri_pipeline\pipeline.py", line 2, in <module>
    from .nodes import data_cleaning, split_data, normalise_data, define_model, windowing, train_model, evaluate_model, save_model
ImportError: cannot import name 'windowing' from 'tentative_agri_proj.pipelines.agri_pipeline.nodes' (C:\Users\paolo\Documents\GitHub\tentative_agri_proj\src\tentative_agri_proj\pipelines\agri_pipeline\nodes.py)

  warnings.warn(

2024-02-08 16:46:15,144 - kedro.framework.session.session - INFO - Kedro project tentative_agri_proj
2024-02-08 16:46:20,849 - tensorflow - WARNING - From C:\Users\paolo\Documents\GitHub\tentative_agri_proj\.venv\Lib\site-packages\keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

2024-02-08 16:46:21,189 - py.warnings - WARNING - C:\Users\paolo\Documents\GitHub\tentative_agri_proj\.venv\Lib\site-packages\kedro\framework\project\__init__.py:366: UserWarning: An error occurred while importing the 'tentative_agri_proj.pipelines.agri_pipeline' module. Nothing defined therein will be returned by 'find_pipelines'.

Traceback (most recent call last):
  File "C:\Users\paolo\Documents\GitHub\tentative_agri_proj\.venv\Lib\site-packages\kedro\framework\project\__init__.py", line 364, in find_pipelines
    pipeline_module = importlib.import_module(pipeline_module_name)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\paolo\AppData\Local\Programs\Python\Python311\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\paolo\Documents\GitHub\tentative_agri_proj\src\tentative_agri_proj\pipelines\agri_pipeline\__init__.py", line 1, in <module>
    from .pipeline import create_pipeline  # NOQA
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\paolo\Documents\GitHub\tentative_agri_proj\src\tentative_agri_proj\pipelines\agri_pipeline\pipeline.py", line 2, in <module>
    from .nodes import data_cleaning, split_data, normalise_data, define_model, windowing, train_model, evaluate_model, save_model
ImportError: cannot import name 'windowing' from 'tentative_agri_proj.pipelines.agri_pipeline.nodes' (C:\Users\paolo\Documents\GitHub\tentative_agri_proj\src\tentative_agri_proj\pipelines\agri_pipeline\nodes.py)

  warnings.warn(

2024-02-08 16:47:11,706 - kedro.framework.session.session - INFO - Kedro project tentative_agri_proj
2024-02-08 16:47:18,370 - tensorflow - WARNING - From C:\Users\paolo\Documents\GitHub\tentative_agri_proj\.venv\Lib\site-packages\keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

2024-02-08 16:47:18,837 - py.warnings - WARNING - C:\Users\paolo\Documents\GitHub\tentative_agri_proj\.venv\Lib\site-packages\kedro\framework\project\__init__.py:366: UserWarning: An error occurred while importing the 'tentative_agri_proj.pipelines.agri_pipeline' module. Nothing defined therein will be returned by 'find_pipelines'.

Traceback (most recent call last):
  File "C:\Users\paolo\Documents\GitHub\tentative_agri_proj\.venv\Lib\site-packages\kedro\framework\project\__init__.py", line 364, in find_pipelines
    pipeline_module = importlib.import_module(pipeline_module_name)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\paolo\AppData\Local\Programs\Python\Python311\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\paolo\Documents\GitHub\tentative_agri_proj\src\tentative_agri_proj\pipelines\agri_pipeline\__init__.py", line 1, in <module>
    from .pipeline import create_pipeline  # NOQA
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\paolo\Documents\GitHub\tentative_agri_proj\src\tentative_agri_proj\pipelines\agri_pipeline\pipeline.py", line 2, in <module>
    from .nodes import data_cleaning, split_data, normalise_data, define_model, windowing, train_model, evaluate_model, save_model
ImportError: cannot import name 'windowing' from 'tentative_agri_proj.pipelines.agri_pipeline.nodes' (C:\Users\paolo\Documents\GitHub\tentative_agri_proj\src\tentative_agri_proj\pipelines\agri_pipeline\nodes.py)

  warnings.warn(

2024-02-08 16:49:50,243 - kedro.framework.session.session - INFO - Kedro project tentative_agri_proj
2024-02-08 16:49:55,585 - tensorflow - WARNING - From C:\Users\paolo\Documents\GitHub\tentative_agri_proj\.venv\Lib\site-packages\keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

2024-02-08 16:49:55,946 - py.warnings - WARNING - C:\Users\paolo\Documents\GitHub\tentative_agri_proj\.venv\Lib\site-packages\kedro\framework\project\__init__.py:366: UserWarning: An error occurred while importing the 'tentative_agri_proj.pipelines.agri_pipeline' module. Nothing defined therein will be returned by 'find_pipelines'.

Traceback (most recent call last):
  File "C:\Users\paolo\Documents\GitHub\tentative_agri_proj\.venv\Lib\site-packages\kedro\framework\project\__init__.py", line 364, in find_pipelines
    pipeline_module = importlib.import_module(pipeline_module_name)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\paolo\AppData\Local\Programs\Python\Python311\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\paolo\Documents\GitHub\tentative_agri_proj\src\tentative_agri_proj\pipelines\agri_pipeline\__init__.py", line 1, in <module>
    from .pipeline import create_pipeline  # NOQA
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\paolo\Documents\GitHub\tentative_agri_proj\src\tentative_agri_proj\pipelines\agri_pipeline\pipeline.py", line 2, in <module>
    from .nodes import data_cleaning, split_data, normalise_data, define_model, windowing, train_model, evaluate_model, save_model
ImportError: cannot import name 'windowing' from 'tentative_agri_proj.pipelines.agri_pipeline.nodes' (C:\Users\paolo\Documents\GitHub\tentative_agri_proj\src\tentative_agri_proj\pipelines\agri_pipeline\nodes.py)

  warnings.warn(

2024-02-08 16:52:40,886 - kedro.framework.session.session - INFO - Kedro project tentative_agri_proj
2024-02-08 16:52:46,056 - tensorflow - WARNING - From C:\Users\paolo\Documents\GitHub\tentative_agri_proj\.venv\Lib\site-packages\keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

2024-02-08 16:52:46,417 - py.warnings - WARNING - C:\Users\paolo\Documents\GitHub\tentative_agri_proj\.venv\Lib\site-packages\kedro\framework\project\__init__.py:366: UserWarning: An error occurred while importing the 'tentative_agri_proj.pipelines.agri_pipeline' module. Nothing defined therein will be returned by 'find_pipelines'.

Traceback (most recent call last):
  File "C:\Users\paolo\Documents\GitHub\tentative_agri_proj\.venv\Lib\site-packages\kedro\framework\project\__init__.py", line 364, in find_pipelines
    pipeline_module = importlib.import_module(pipeline_module_name)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\paolo\AppData\Local\Programs\Python\Python311\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\paolo\Documents\GitHub\tentative_agri_proj\src\tentative_agri_proj\pipelines\agri_pipeline\__init__.py", line 1, in <module>
    from .pipeline import create_pipeline  # NOQA
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\paolo\Documents\GitHub\tentative_agri_proj\src\tentative_agri_proj\pipelines\agri_pipeline\pipeline.py", line 2, in <module>
    from .nodes import data_cleaning, split_data, normalise_data, define_model, windowing, train_model, evaluate_model, save_model
ImportError: cannot import name 'windowing' from 'tentative_agri_proj.pipelines.agri_pipeline.nodes' (C:\Users\paolo\Documents\GitHub\tentative_agri_proj\src\tentative_agri_proj\pipelines\agri_pipeline\nodes.py)

  warnings.warn(

2024-02-08 16:58:16,348 - kedro.framework.session.session - INFO - Kedro project tentative_agri_proj
2024-02-08 16:58:21,660 - tensorflow - WARNING - From C:\Users\paolo\Documents\GitHub\tentative_agri_proj\.venv\Lib\site-packages\keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

2024-02-08 16:58:22,013 - py.warnings - WARNING - C:\Users\paolo\Documents\GitHub\tentative_agri_proj\.venv\Lib\site-packages\kedro\framework\project\__init__.py:366: UserWarning: An error occurred while importing the 'tentative_agri_proj.pipelines.main_pipeline' module. Nothing defined therein will be returned by 'find_pipelines'.

Traceback (most recent call last):
  File "C:\Users\paolo\Documents\GitHub\tentative_agri_proj\.venv\Lib\site-packages\kedro\framework\project\__init__.py", line 364, in find_pipelines
    pipeline_module = importlib.import_module(pipeline_module_name)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\paolo\AppData\Local\Programs\Python\Python311\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\paolo\Documents\GitHub\tentative_agri_proj\src\tentative_agri_proj\pipelines\main_pipeline\__init__.py", line 1, in <module>
    from .pipeline import create_pipeline  # NOQA
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\paolo\Documents\GitHub\tentative_agri_proj\src\tentative_agri_proj\pipelines\main_pipeline\pipeline.py", line 2, in <module>
    from .nodes import data_cleaning, split_data, normalise_data, define_model, windowing, train_model, evaluate_model, save_model
ImportError: cannot import name 'windowing' from 'tentative_agri_proj.pipelines.main_pipeline.nodes' (C:\Users\paolo\Documents\GitHub\tentative_agri_proj\src\tentative_agri_proj\pipelines\main_pipeline\nodes.py)

  warnings.warn(

2024-02-08 17:10:52,601 - kedro.framework.session.session - INFO - Kedro project tentative_agri_proj
2024-02-08 17:10:57,723 - tensorflow - WARNING - From C:\Users\paolo\Documents\GitHub\tentative_agri_proj\.venv\Lib\site-packages\keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

2024-02-08 17:10:58,090 - py.warnings - WARNING - C:\Users\paolo\Documents\GitHub\tentative_agri_proj\.venv\Lib\site-packages\kedro\framework\project\__init__.py:366: UserWarning: An error occurred while importing the 'tentative_agri_proj.pipelines.main_pipeline' module. Nothing defined therein will be returned by 'find_pipelines'.

Traceback (most recent call last):
  File "C:\Users\paolo\Documents\GitHub\tentative_agri_proj\.venv\Lib\site-packages\kedro\framework\project\__init__.py", line 364, in find_pipelines
    pipeline_module = importlib.import_module(pipeline_module_name)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\paolo\AppData\Local\Programs\Python\Python311\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\paolo\Documents\GitHub\tentative_agri_proj\src\tentative_agri_proj\pipelines\main_pipeline\__init__.py", line 1, in <module>
    from .pipeline import create_pipeline  # NOQA
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\paolo\Documents\GitHub\tentative_agri_proj\src\tentative_agri_proj\pipelines\main_pipeline\pipeline.py", line 2, in <module>
    from .nodes import data_cleaning, split_data, normalise_data, define_model, windowing, train_model, evaluate_model, save_model
ImportError: cannot import name 'windowing' from 'tentative_agri_proj.pipelines.main_pipeline.nodes' (C:\Users\paolo\Documents\GitHub\tentative_agri_proj\src\tentative_agri_proj\pipelines\main_pipeline\nodes.py)

  warnings.warn(

2024-02-08 17:22:41,942 - kedro.framework.session.session - INFO - Kedro project tentative_agri_proj
2024-02-08 17:22:47,079 - tensorflow - WARNING - From C:\Users\paolo\Documents\GitHub\tentative_agri_proj\.venv\Lib\site-packages\keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

2024-02-08 17:22:47,438 - py.warnings - WARNING - C:\Users\paolo\Documents\GitHub\tentative_agri_proj\.venv\Lib\site-packages\kedro\framework\project\__init__.py:366: UserWarning: An error occurred while importing the 'tentative_agri_proj.pipelines.main_pipeline' module. Nothing defined therein will be returned by 'find_pipelines'.

Traceback (most recent call last):
  File "C:\Users\paolo\Documents\GitHub\tentative_agri_proj\.venv\Lib\site-packages\kedro\framework\project\__init__.py", line 364, in find_pipelines
    pipeline_module = importlib.import_module(pipeline_module_name)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\paolo\AppData\Local\Programs\Python\Python311\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\paolo\Documents\GitHub\tentative_agri_proj\src\tentative_agri_proj\pipelines\main_pipeline\__init__.py", line 1, in <module>
    from .pipeline import create_pipeline  # NOQA
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\paolo\Documents\GitHub\tentative_agri_proj\src\tentative_agri_proj\pipelines\main_pipeline\pipeline.py", line 2, in <module>
    from .nodes import data_cleaning, split_data, normalise_data, define_model, windowing, train_model, evaluate_model, save_model
ImportError: cannot import name 'windowing' from 'tentative_agri_proj.pipelines.main_pipeline.nodes' (C:\Users\paolo\Documents\GitHub\tentative_agri_proj\src\tentative_agri_proj\pipelines\main_pipeline\nodes.py)

  warnings.warn(

2024-02-08 17:37:24,254 - kedro.framework.session.session - INFO - Kedro project tentative_agri_proj
2024-02-08 17:37:29,293 - tensorflow - WARNING - From C:\Users\paolo\Documents\GitHub\tentative_agri_proj\.venv\Lib\site-packages\keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

2024-02-08 17:38:00,501 - kedro.framework.session.session - INFO - Kedro project tentative_agri_proj
2024-02-08 17:38:05,531 - tensorflow - WARNING - From C:\Users\paolo\Documents\GitHub\tentative_agri_proj\.venv\Lib\site-packages\keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

2024-02-09 09:29:35,385 - kedro.framework.session.session - INFO - Kedro project tentative_agri_proj
2024-02-09 09:29:48,843 - tensorflow - WARNING - From C:\Users\paolo\Documents\GitHub\tentative_agri_proj\.venv\Lib\site-packages\keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

2024-02-09 09:32:00,102 - kedro.framework.session.session - INFO - Kedro project tentative_agri_proj
2024-02-09 09:32:05,240 - tensorflow - WARNING - From C:\Users\paolo\Documents\GitHub\tentative_agri_proj\.venv\Lib\site-packages\keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

2024-02-09 09:39:51,495 - kedro.framework.session.session - INFO - Kedro project tentative_agri_proj
2024-02-09 09:39:57,738 - tensorflow - WARNING - From C:\Users\paolo\Documents\GitHub\tentative_agri_proj\.venv\Lib\site-packages\keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

2024-02-09 09:40:17,006 - kedro.framework.session.session - INFO - Kedro project tentative_agri_proj
2024-02-09 09:40:22,228 - tensorflow - WARNING - From C:\Users\paolo\Documents\GitHub\tentative_agri_proj\.venv\Lib\site-packages\keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

2024-02-09 09:41:52,759 - kedro.framework.session.session - INFO - Kedro project tentative_agri_proj
2024-02-09 09:41:57,975 - tensorflow - WARNING - From C:\Users\paolo\Documents\GitHub\tentative_agri_proj\.venv\Lib\site-packages\keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

2024-02-09 09:41:58,393 - kedro.io.data_catalog - INFO - Loading data from 'logger_3_betula' (CSVDataSet)...
2024-02-09 09:41:58,637 - kedro.pipeline.node - INFO - Running node: data_cleaning_node: data_cleaning([logger_3_betula]) -> [logger_3_betula_cleaned]
2024-02-09 09:41:58,808 - kedro.io.data_catalog - INFO - Saving data to 'logger_3_betula_cleaned' (MemoryDataset)...
2024-02-09 09:41:58,825 - kedro.runner.sequential_runner - INFO - Completed 1 out of 10 tasks
2024-02-09 09:41:58,829 - kedro.pipeline.node - INFO - Running node: define_model_node: define_model(None) -> [model]
2024-02-09 09:41:59,245 - tensorflow - WARNING - From C:\Users\paolo\Documents\GitHub\tentative_agri_proj\.venv\Lib\site-packages\keras\src\utils\tf_utils.py:585: The name tf.executing_eagerly_outside_functions is deprecated. Please use tf.compat.v1.executing_eagerly_outside_functions instead.

2024-02-09 09:41:59,392 - kedro.io.data_catalog - INFO - Saving data to 'model' (MemoryDataset)...
2024-02-09 09:41:59,408 - kedro.runner.sequential_runner - WARNING - There are 9 nodes that have not run.
You can resume the pipeline run from the nearest nodes with persisted inputs by adding the following argument to your previous command:
  --from-nodes "data_cleaning_node"
2024-02-09 09:44:28,727 - kedro.framework.session.session - INFO - Kedro project tentative_agri_proj
2024-02-09 09:44:33,958 - tensorflow - WARNING - From C:\Users\paolo\Documents\GitHub\tentative_agri_proj\.venv\Lib\site-packages\keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

2024-02-09 09:44:34,346 - kedro.io.data_catalog - INFO - Loading data from 'logger_3_betula' (CSVDataSet)...
2024-02-09 09:44:34,510 - kedro.pipeline.node - INFO - Running node: data_cleaning_node: data_cleaning([logger_3_betula]) -> [logger_3_betula_cleaned]
2024-02-09 09:44:34,646 - kedro.io.data_catalog - INFO - Saving data to 'logger_3_betula_cleaned' (MemoryDataset)...
2024-02-09 09:44:34,646 - kedro.runner.sequential_runner - INFO - Completed 1 out of 10 tasks
2024-02-09 09:44:34,663 - kedro.pipeline.node - INFO - Running node: define_model_node: define_model(None) -> [model]
2024-02-09 09:44:34,845 - tensorflow - WARNING - From C:\Users\paolo\Documents\GitHub\tentative_agri_proj\.venv\Lib\site-packages\keras\src\utils\tf_utils.py:585: The name tf.executing_eagerly_outside_functions is deprecated. Please use tf.compat.v1.executing_eagerly_outside_functions instead.

2024-02-09 09:44:34,995 - kedro.io.data_catalog - INFO - Saving data to 'model' (MemoryDataset)...
2024-02-09 09:44:35,011 - kedro.runner.sequential_runner - WARNING - There are 9 nodes that have not run.
You can resume the pipeline run from the nearest nodes with persisted inputs by adding the following argument to your previous command:
  --from-nodes "data_cleaning_node"
2024-02-09 09:45:45,689 - kedro.framework.session.session - INFO - Kedro project tentative_agri_proj
2024-02-09 09:45:50,844 - tensorflow - WARNING - From C:\Users\paolo\Documents\GitHub\tentative_agri_proj\.venv\Lib\site-packages\keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

2024-02-09 09:45:51,267 - kedro.io.data_catalog - INFO - Loading data from 'logger_3_betula' (CSVDataSet)...
2024-02-09 09:45:51,421 - kedro.pipeline.node - INFO - Running node: data_cleaning_node: data_cleaning([logger_3_betula]) -> [logger_3_betula_cleaned]
2024-02-09 09:45:51,541 - kedro.io.data_catalog - INFO - Saving data to 'logger_3_betula_cleaned' (MemoryDataset)...
2024-02-09 09:45:51,557 - kedro.runner.sequential_runner - INFO - Completed 1 out of 9 tasks
2024-02-09 09:45:51,573 - kedro.pipeline.node - INFO - Running node: define_model_node: define_model(None) -> [model]
2024-02-09 09:45:51,756 - tensorflow - WARNING - From C:\Users\paolo\Documents\GitHub\tentative_agri_proj\.venv\Lib\site-packages\keras\src\utils\tf_utils.py:585: The name tf.executing_eagerly_outside_functions is deprecated. Please use tf.compat.v1.executing_eagerly_outside_functions instead.

2024-02-09 09:45:51,891 - kedro.io.data_catalog - INFO - Saving data to 'model' (MemoryDataset)...
2024-02-09 09:45:51,906 - kedro.runner.sequential_runner - WARNING - There are 8 nodes that have not run.
You can resume the pipeline run from the nearest nodes with persisted inputs by adding the following argument to your previous command:
  --from-nodes "data_cleaning_node"
2024-02-09 09:57:06,752 - kedro.framework.session.session - INFO - Kedro project tentative_agri_proj
2024-02-09 09:57:11,969 - tensorflow - WARNING - From C:\Users\paolo\Documents\GitHub\tentative_agri_proj\.venv\Lib\site-packages\keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

2024-02-09 09:57:12,391 - kedro.io.data_catalog - INFO - Loading data from 'logger_3_betula' (CSVDataSet)...
2024-02-09 09:57:12,564 - kedro.pipeline.node - INFO - Running node: data_cleaning_node: data_cleaning([logger_3_betula]) -> [logger_3_betula_cleaned]
2024-02-09 09:57:12,683 - kedro.io.data_catalog - INFO - Saving data to 'logger_3_betula_cleaned' (MemoryDataset)...
2024-02-09 09:57:12,701 - kedro.runner.sequential_runner - INFO - Completed 1 out of 1 tasks
2024-02-09 09:57:12,701 - kedro.runner.sequential_runner - INFO - Pipeline execution completed successfully.
2024-02-09 09:57:12,701 - kedro.io.data_catalog - INFO - Loading data from 'logger_3_betula_cleaned' (MemoryDataset)...
2024-02-09 09:57:37,795 - kedro.framework.session.session - INFO - Kedro project tentative_agri_proj
2024-02-09 09:57:43,688 - tensorflow - WARNING - From C:\Users\paolo\Documents\GitHub\tentative_agri_proj\.venv\Lib\site-packages\keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

2024-02-09 09:57:44,094 - kedro.io.data_catalog - INFO - Loading data from 'logger_3_betula' (CSVDataSet)...
2024-02-09 09:57:44,254 - kedro.pipeline.node - INFO - Running node: data_cleaning_node: data_cleaning([logger_3_betula]) -> [logger_3_betula_cleaned]
2024-02-09 09:57:44,394 - kedro.io.data_catalog - INFO - Saving data to 'logger_3_betula_cleaned' (MemoryDataset)...
2024-02-09 09:57:44,394 - kedro.runner.sequential_runner - INFO - Completed 1 out of 2 tasks
2024-02-09 09:57:44,409 - kedro.io.data_catalog - INFO - Loading data from 'logger_3_betula_cleaned' (MemoryDataset)...
2024-02-09 09:57:44,425 - kedro.pipeline.node - INFO - Running node: split_data_node: split_data([logger_3_betula_cleaned]) -> [train_logger_3_betula,val_logger_3_betula,test_logger_3_betula]
2024-02-09 09:57:44,475 - kedro.io.data_catalog - INFO - Saving data to 'train_logger_3_betula' (MemoryDataset)...
2024-02-09 09:57:44,494 - kedro.io.data_catalog - INFO - Saving data to 'val_logger_3_betula' (MemoryDataset)...
2024-02-09 09:57:44,508 - kedro.io.data_catalog - INFO - Saving data to 'test_logger_3_betula' (MemoryDataset)...
2024-02-09 09:57:44,524 - kedro.runner.sequential_runner - INFO - Completed 2 out of 2 tasks
2024-02-09 09:57:44,524 - kedro.runner.sequential_runner - INFO - Pipeline execution completed successfully.
2024-02-09 09:57:44,540 - kedro.io.data_catalog - INFO - Loading data from 'val_logger_3_betula' (MemoryDataset)...
2024-02-09 09:57:44,542 - kedro.io.data_catalog - INFO - Loading data from 'test_logger_3_betula' (MemoryDataset)...
2024-02-09 09:57:44,542 - kedro.io.data_catalog - INFO - Loading data from 'train_logger_3_betula' (MemoryDataset)...
2024-02-09 09:57:53,398 - kedro.framework.session.session - INFO - Kedro project tentative_agri_proj
2024-02-09 09:57:58,494 - tensorflow - WARNING - From C:\Users\paolo\Documents\GitHub\tentative_agri_proj\.venv\Lib\site-packages\keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

2024-02-09 09:57:58,901 - kedro.io.data_catalog - INFO - Loading data from 'logger_3_betula' (CSVDataSet)...
2024-02-09 09:57:59,055 - kedro.pipeline.node - INFO - Running node: data_cleaning_node: data_cleaning([logger_3_betula]) -> [logger_3_betula_cleaned]
2024-02-09 09:57:59,189 - kedro.io.data_catalog - INFO - Saving data to 'logger_3_betula_cleaned' (MemoryDataset)...
2024-02-09 09:57:59,189 - kedro.runner.sequential_runner - INFO - Completed 1 out of 3 tasks
2024-02-09 09:57:59,208 - kedro.io.data_catalog - INFO - Loading data from 'logger_3_betula_cleaned' (MemoryDataset)...
2024-02-09 09:57:59,227 - kedro.pipeline.node - INFO - Running node: split_data_node: split_data([logger_3_betula_cleaned]) -> [train_logger_3_betula,val_logger_3_betula,test_logger_3_betula]
2024-02-09 09:57:59,275 - kedro.io.data_catalog - INFO - Saving data to 'train_logger_3_betula' (MemoryDataset)...
2024-02-09 09:57:59,292 - kedro.io.data_catalog - INFO - Saving data to 'val_logger_3_betula' (MemoryDataset)...
2024-02-09 09:57:59,328 - kedro.io.data_catalog - INFO - Saving data to 'test_logger_3_betula' (MemoryDataset)...
2024-02-09 09:57:59,339 - kedro.runner.sequential_runner - INFO - Completed 2 out of 3 tasks
2024-02-09 09:57:59,342 - kedro.io.data_catalog - INFO - Loading data from 'train_logger_3_betula' (MemoryDataset)...
2024-02-09 09:57:59,359 - kedro.io.data_catalog - INFO - Loading data from 'val_logger_3_betula' (MemoryDataset)...
2024-02-09 09:57:59,360 - kedro.io.data_catalog - INFO - Loading data from 'test_logger_3_betula' (MemoryDataset)...
2024-02-09 09:57:59,408 - kedro.pipeline.node - INFO - Running node: normalise_data_node: normalise_data([train_logger_3_betula,val_logger_3_betula,test_logger_3_betula]) -> [train_logger_3_betula_norm,val_logger_3_betula_norm,test_logger_3_betula_norm]
2024-02-09 09:57:59,493 - kedro.io.data_catalog - INFO - Saving data to 'train_logger_3_betula_norm' (MemoryDataset)...
2024-02-09 09:57:59,510 - kedro.io.data_catalog - INFO - Saving data to 'val_logger_3_betula_norm' (MemoryDataset)...
2024-02-09 09:57:59,527 - kedro.io.data_catalog - INFO - Saving data to 'test_logger_3_betula_norm' (MemoryDataset)...
2024-02-09 09:57:59,527 - kedro.runner.sequential_runner - INFO - Completed 3 out of 3 tasks
2024-02-09 09:57:59,544 - kedro.runner.sequential_runner - INFO - Pipeline execution completed successfully.
2024-02-09 09:57:59,544 - kedro.io.data_catalog - INFO - Loading data from 'val_logger_3_betula_norm' (MemoryDataset)...
2024-02-09 09:57:59,544 - kedro.io.data_catalog - INFO - Loading data from 'train_logger_3_betula_norm' (MemoryDataset)...
2024-02-09 09:57:59,557 - kedro.io.data_catalog - INFO - Loading data from 'test_logger_3_betula_norm' (MemoryDataset)...
2024-02-09 09:58:09,412 - kedro.framework.session.session - INFO - Kedro project tentative_agri_proj
2024-02-09 09:58:14,645 - tensorflow - WARNING - From C:\Users\paolo\Documents\GitHub\tentative_agri_proj\.venv\Lib\site-packages\keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

2024-02-09 09:58:15,028 - kedro.io.data_catalog - INFO - Loading data from 'logger_3_betula' (CSVDataSet)...
2024-02-09 09:58:15,193 - kedro.pipeline.node - INFO - Running node: data_cleaning_node: data_cleaning([logger_3_betula]) -> [logger_3_betula_cleaned]
2024-02-09 09:58:15,327 - kedro.io.data_catalog - INFO - Saving data to 'logger_3_betula_cleaned' (MemoryDataset)...
2024-02-09 09:58:15,342 - kedro.runner.sequential_runner - INFO - Completed 1 out of 4 tasks
2024-02-09 09:58:15,346 - kedro.pipeline.node - INFO - Running node: define_model_node: define_model(None) -> [model]
2024-02-09 09:58:15,539 - tensorflow - WARNING - From C:\Users\paolo\Documents\GitHub\tentative_agri_proj\.venv\Lib\site-packages\keras\src\utils\tf_utils.py:585: The name tf.executing_eagerly_outside_functions is deprecated. Please use tf.compat.v1.executing_eagerly_outside_functions instead.

2024-02-09 09:58:15,673 - kedro.io.data_catalog - INFO - Saving data to 'model' (MemoryDataset)...
2024-02-09 09:58:15,699 - kedro.runner.sequential_runner - WARNING - There are 3 nodes that have not run.
You can resume the pipeline run from the nearest nodes with persisted inputs by adding the following argument to your previous command:
  --from-nodes "data_cleaning_node"
2024-02-09 10:00:42,911 - kedro.framework.session.session - INFO - Kedro project tentative_agri_proj
2024-02-09 10:00:48,144 - tensorflow - WARNING - From C:\Users\paolo\Documents\GitHub\tentative_agri_proj\.venv\Lib\site-packages\keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

2024-02-09 10:00:48,580 - kedro.io.data_catalog - INFO - Loading data from 'logger_3_betula' (CSVDataSet)...
2024-02-09 10:00:48,745 - kedro.pipeline.node - INFO - Running node: data_cleaning_node: data_cleaning([logger_3_betula]) -> [logger_3_betula_cleaned]
2024-02-09 10:00:48,864 - kedro.io.data_catalog - INFO - Saving data to 'logger_3_betula_cleaned' (MemoryDataset)...
2024-02-09 10:00:48,884 - kedro.runner.sequential_runner - INFO - Completed 1 out of 4 tasks
2024-02-09 10:00:48,886 - kedro.pipeline.node - INFO - Running node: define_model_node: define_model(None) -> [model]
2024-02-09 10:00:49,064 - tensorflow - WARNING - From C:\Users\paolo\Documents\GitHub\tentative_agri_proj\.venv\Lib\site-packages\keras\src\utils\tf_utils.py:585: The name tf.executing_eagerly_outside_functions is deprecated. Please use tf.compat.v1.executing_eagerly_outside_functions instead.

2024-02-09 10:00:49,198 - kedro.io.data_catalog - INFO - Saving data to 'model' (MemoryDataset)...
2024-02-09 10:00:49,198 - kedro.runner.sequential_runner - INFO - Completed 2 out of 4 tasks
2024-02-09 10:00:49,213 - kedro.io.data_catalog - INFO - Loading data from 'logger_3_betula_cleaned' (MemoryDataset)...
2024-02-09 10:00:49,234 - kedro.pipeline.node - INFO - Running node: split_data_node: split_data([logger_3_betula_cleaned]) -> [train_logger_3_betula,val_logger_3_betula,test_logger_3_betula]
2024-02-09 10:00:49,284 - kedro.io.data_catalog - INFO - Saving data to 'train_logger_3_betula' (MemoryDataset)...
2024-02-09 10:00:49,302 - kedro.io.data_catalog - INFO - Saving data to 'val_logger_3_betula' (MemoryDataset)...
2024-02-09 10:00:49,317 - kedro.io.data_catalog - INFO - Saving data to 'test_logger_3_betula' (MemoryDataset)...
2024-02-09 10:00:49,334 - kedro.runner.sequential_runner - INFO - Completed 3 out of 4 tasks
2024-02-09 10:00:49,350 - kedro.io.data_catalog - INFO - Loading data from 'train_logger_3_betula' (MemoryDataset)...
2024-02-09 10:00:49,351 - kedro.io.data_catalog - INFO - Loading data from 'val_logger_3_betula' (MemoryDataset)...
2024-02-09 10:00:49,368 - kedro.io.data_catalog - INFO - Loading data from 'test_logger_3_betula' (MemoryDataset)...
2024-02-09 10:00:49,418 - kedro.pipeline.node - INFO - Running node: normalise_data_node: normalise_data([train_logger_3_betula,val_logger_3_betula,test_logger_3_betula]) -> [train_logger_3_betula_norm,val_logger_3_betula_norm,test_logger_3_betula_norm]
2024-02-09 10:00:49,492 - kedro.io.data_catalog - INFO - Saving data to 'train_logger_3_betula_norm' (MemoryDataset)...
2024-02-09 10:00:49,508 - kedro.io.data_catalog - INFO - Saving data to 'val_logger_3_betula_norm' (MemoryDataset)...
2024-02-09 10:00:49,517 - kedro.io.data_catalog - INFO - Saving data to 'test_logger_3_betula_norm' (MemoryDataset)...
2024-02-09 10:00:49,534 - kedro.runner.sequential_runner - INFO - Completed 4 out of 4 tasks
2024-02-09 10:00:49,534 - kedro.runner.sequential_runner - INFO - Pipeline execution completed successfully.
2024-02-09 10:00:49,534 - kedro.io.data_catalog - INFO - Loading data from 'val_logger_3_betula_norm' (MemoryDataset)...
2024-02-09 10:00:49,551 - kedro.io.data_catalog - INFO - Loading data from 'test_logger_3_betula_norm' (MemoryDataset)...
2024-02-09 10:00:49,551 - kedro.io.data_catalog - INFO - Loading data from 'train_logger_3_betula_norm' (MemoryDataset)...
2024-02-09 10:00:49,551 - kedro.io.data_catalog - INFO - Loading data from 'model' (MemoryDataset)...
2024-02-09 10:01:56,001 - kedro.framework.session.session - INFO - Kedro project tentative_agri_proj
2024-02-09 10:02:01,313 - tensorflow - WARNING - From C:\Users\paolo\Documents\GitHub\tentative_agri_proj\.venv\Lib\site-packages\keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

2024-02-09 10:02:01,775 - kedro.io.data_catalog - INFO - Loading data from 'logger_3_betula' (CSVDataSet)...
2024-02-09 10:02:01,990 - kedro.pipeline.node - INFO - Running node: data_cleaning_node: data_cleaning([logger_3_betula]) -> [logger_3_betula_cleaned]
2024-02-09 10:02:02,144 - kedro.io.data_catalog - INFO - Saving data to 'logger_3_betula_cleaned' (MemoryDataset)...
2024-02-09 10:02:02,164 - kedro.runner.sequential_runner - INFO - Completed 1 out of 7 tasks
2024-02-09 10:02:02,164 - kedro.pipeline.node - INFO - Running node: define_model_node: define_model(None) -> [model]
2024-02-09 10:02:02,346 - tensorflow - WARNING - From C:\Users\paolo\Documents\GitHub\tentative_agri_proj\.venv\Lib\site-packages\keras\src\utils\tf_utils.py:585: The name tf.executing_eagerly_outside_functions is deprecated. Please use tf.compat.v1.executing_eagerly_outside_functions instead.

2024-02-09 10:02:02,478 - kedro.io.data_catalog - INFO - Saving data to 'model' (MemoryDataset)...
2024-02-09 10:02:02,494 - kedro.runner.sequential_runner - INFO - Completed 2 out of 7 tasks
2024-02-09 10:02:02,494 - kedro.io.data_catalog - INFO - Loading data from 'logger_3_betula_cleaned' (MemoryDataset)...
2024-02-09 10:02:02,515 - kedro.pipeline.node - INFO - Running node: split_data_node: split_data([logger_3_betula_cleaned]) -> [train_logger_3_betula,val_logger_3_betula,test_logger_3_betula]
2024-02-09 10:02:02,565 - kedro.io.data_catalog - INFO - Saving data to 'train_logger_3_betula' (MemoryDataset)...
2024-02-09 10:02:02,584 - kedro.io.data_catalog - INFO - Saving data to 'val_logger_3_betula' (MemoryDataset)...
2024-02-09 10:02:02,598 - kedro.io.data_catalog - INFO - Saving data to 'test_logger_3_betula' (MemoryDataset)...
2024-02-09 10:02:02,616 - kedro.runner.sequential_runner - INFO - Completed 3 out of 7 tasks
2024-02-09 10:02:02,630 - kedro.io.data_catalog - INFO - Loading data from 'train_logger_3_betula' (MemoryDataset)...
2024-02-09 10:02:02,631 - kedro.io.data_catalog - INFO - Loading data from 'val_logger_3_betula' (MemoryDataset)...
2024-02-09 10:02:02,649 - kedro.io.data_catalog - INFO - Loading data from 'test_logger_3_betula' (MemoryDataset)...
2024-02-09 10:02:02,682 - kedro.pipeline.node - INFO - Running node: normalise_data_node: normalise_data([train_logger_3_betula,val_logger_3_betula,test_logger_3_betula]) -> [train_logger_3_betula_norm,val_logger_3_betula_norm,test_logger_3_betula_norm]
2024-02-09 10:02:02,764 - kedro.io.data_catalog - INFO - Saving data to 'train_logger_3_betula_norm' (MemoryDataset)...
2024-02-09 10:02:02,782 - kedro.io.data_catalog - INFO - Saving data to 'val_logger_3_betula_norm' (MemoryDataset)...
2024-02-09 10:02:02,798 - kedro.io.data_catalog - INFO - Saving data to 'test_logger_3_betula_norm' (MemoryDataset)...
2024-02-09 10:02:02,798 - kedro.runner.sequential_runner - INFO - Completed 4 out of 7 tasks
2024-02-09 10:02:02,815 - kedro.io.data_catalog - INFO - Loading data from 'test_logger_3_betula_norm' (MemoryDataset)...
2024-02-09 10:02:02,832 - kedro.pipeline.node - INFO - Running node: windowing_test_node: get_windowed_data([test_logger_3_betula_norm]) -> [X_test,Y_test]
2024-02-09 10:02:05,422 - kedro.io.data_catalog - INFO - Saving data to 'X_test' (MemoryDataset)...
2024-02-09 10:02:05,422 - kedro.io.data_catalog - INFO - Saving data to 'Y_test' (MemoryDataset)...
2024-02-09 10:02:05,441 - kedro.runner.sequential_runner - INFO - Completed 5 out of 7 tasks
2024-02-09 10:02:05,444 - kedro.io.data_catalog - INFO - Loading data from 'train_logger_3_betula_norm' (MemoryDataset)...
2024-02-09 10:02:05,462 - kedro.pipeline.node - INFO - Running node: windowing_train_node: get_windowed_data([train_logger_3_betula_norm]) -> [X_train,Y_train]
2024-02-09 10:02:22,673 - kedro.io.data_catalog - INFO - Saving data to 'X_train' (MemoryDataset)...
2024-02-09 10:02:22,700 - kedro.io.data_catalog - INFO - Saving data to 'Y_train' (MemoryDataset)...
2024-02-09 10:02:22,700 - kedro.runner.sequential_runner - INFO - Completed 6 out of 7 tasks
2024-02-09 10:02:22,713 - kedro.io.data_catalog - INFO - Loading data from 'val_logger_3_betula_norm' (MemoryDataset)...
2024-02-09 10:02:22,730 - kedro.pipeline.node - INFO - Running node: windowing_val_node: get_windowed_data([val_logger_3_betula_norm]) -> [X_val,Y_val]
2024-02-09 10:02:28,015 - kedro.io.data_catalog - INFO - Saving data to 'X_val' (MemoryDataset)...
2024-02-09 10:02:28,030 - kedro.io.data_catalog - INFO - Saving data to 'Y_val' (MemoryDataset)...
2024-02-09 10:02:28,037 - kedro.runner.sequential_runner - INFO - Completed 7 out of 7 tasks
2024-02-09 10:02:28,041 - kedro.runner.sequential_runner - INFO - Pipeline execution completed successfully.
2024-02-09 10:02:28,041 - kedro.io.data_catalog - INFO - Loading data from 'model' (MemoryDataset)...
2024-02-09 10:02:28,041 - kedro.io.data_catalog - INFO - Loading data from 'X_train' (MemoryDataset)...
2024-02-09 10:02:28,060 - kedro.io.data_catalog - INFO - Loading data from 'Y_test' (MemoryDataset)...
2024-02-09 10:02:28,060 - kedro.io.data_catalog - INFO - Loading data from 'X_val' (MemoryDataset)...
2024-02-09 10:02:28,075 - kedro.io.data_catalog - INFO - Loading data from 'Y_val' (MemoryDataset)...
2024-02-09 10:02:28,075 - kedro.io.data_catalog - INFO - Loading data from 'Y_train' (MemoryDataset)...
2024-02-09 10:02:28,075 - kedro.io.data_catalog - INFO - Loading data from 'X_test' (MemoryDataset)...
2024-02-09 10:02:37,521 - kedro.framework.session.session - INFO - Kedro project tentative_agri_proj
2024-02-09 10:02:43,405 - tensorflow - WARNING - From C:\Users\paolo\Documents\GitHub\tentative_agri_proj\.venv\Lib\site-packages\keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

2024-02-09 10:02:43,842 - kedro.io.data_catalog - INFO - Loading data from 'logger_3_betula' (CSVDataSet)...
2024-02-09 10:02:44,019 - kedro.pipeline.node - INFO - Running node: data_cleaning_node: data_cleaning([logger_3_betula]) -> [logger_3_betula_cleaned]
2024-02-09 10:02:44,141 - kedro.io.data_catalog - INFO - Saving data to 'logger_3_betula_cleaned' (MemoryDataset)...
2024-02-09 10:02:44,160 - kedro.runner.sequential_runner - INFO - Completed 1 out of 8 tasks
2024-02-09 10:02:44,160 - kedro.pipeline.node - INFO - Running node: define_model_node: define_model(None) -> [model]
2024-02-09 10:02:44,357 - tensorflow - WARNING - From C:\Users\paolo\Documents\GitHub\tentative_agri_proj\.venv\Lib\site-packages\keras\src\utils\tf_utils.py:585: The name tf.executing_eagerly_outside_functions is deprecated. Please use tf.compat.v1.executing_eagerly_outside_functions instead.

2024-02-09 10:02:44,489 - kedro.io.data_catalog - INFO - Saving data to 'model' (MemoryDataset)...
2024-02-09 10:02:44,504 - kedro.runner.sequential_runner - INFO - Completed 2 out of 8 tasks
2024-02-09 10:02:44,504 - kedro.io.data_catalog - INFO - Loading data from 'logger_3_betula_cleaned' (MemoryDataset)...
2024-02-09 10:02:44,527 - kedro.pipeline.node - INFO - Running node: split_data_node: split_data([logger_3_betula_cleaned]) -> [train_logger_3_betula,val_logger_3_betula,test_logger_3_betula]
2024-02-09 10:02:44,576 - kedro.io.data_catalog - INFO - Saving data to 'train_logger_3_betula' (MemoryDataset)...
2024-02-09 10:02:44,609 - kedro.io.data_catalog - INFO - Saving data to 'val_logger_3_betula' (MemoryDataset)...
2024-02-09 10:02:44,664 - kedro.io.data_catalog - INFO - Saving data to 'test_logger_3_betula' (MemoryDataset)...
2024-02-09 10:02:44,709 - kedro.runner.sequential_runner - INFO - Completed 3 out of 8 tasks
2024-02-09 10:02:44,709 - kedro.io.data_catalog - INFO - Loading data from 'train_logger_3_betula' (MemoryDataset)...
2024-02-09 10:02:44,723 - kedro.io.data_catalog - INFO - Loading data from 'val_logger_3_betula' (MemoryDataset)...
2024-02-09 10:02:44,728 - kedro.io.data_catalog - INFO - Loading data from 'test_logger_3_betula' (MemoryDataset)...
2024-02-09 10:02:44,775 - kedro.pipeline.node - INFO - Running node: normalise_data_node: normalise_data([train_logger_3_betula,val_logger_3_betula,test_logger_3_betula]) -> [train_logger_3_betula_norm,val_logger_3_betula_norm,test_logger_3_betula_norm]
2024-02-09 10:02:44,841 - kedro.io.data_catalog - INFO - Saving data to 'train_logger_3_betula_norm' (MemoryDataset)...
2024-02-09 10:02:44,869 - kedro.io.data_catalog - INFO - Saving data to 'val_logger_3_betula_norm' (MemoryDataset)...
2024-02-09 10:02:44,892 - kedro.io.data_catalog - INFO - Saving data to 'test_logger_3_betula_norm' (MemoryDataset)...
2024-02-09 10:02:44,892 - kedro.runner.sequential_runner - INFO - Completed 4 out of 8 tasks
2024-02-09 10:02:44,892 - kedro.io.data_catalog - INFO - Loading data from 'test_logger_3_betula_norm' (MemoryDataset)...
2024-02-09 10:02:44,929 - kedro.pipeline.node - INFO - Running node: windowing_test_node: get_windowed_data([test_logger_3_betula_norm]) -> [X_test,Y_test]
2024-02-09 10:02:47,820 - kedro.io.data_catalog - INFO - Saving data to 'X_test' (MemoryDataset)...
2024-02-09 10:02:47,820 - kedro.io.data_catalog - INFO - Saving data to 'Y_test' (MemoryDataset)...
2024-02-09 10:02:47,820 - kedro.runner.sequential_runner - INFO - Completed 5 out of 8 tasks
2024-02-09 10:02:47,834 - kedro.io.data_catalog - INFO - Loading data from 'train_logger_3_betula_norm' (MemoryDataset)...
2024-02-09 10:02:47,856 - kedro.pipeline.node - INFO - Running node: windowing_train_node: get_windowed_data([train_logger_3_betula_norm]) -> [X_train,Y_train]
2024-02-09 10:03:05,829 - kedro.io.data_catalog - INFO - Saving data to 'X_train' (MemoryDataset)...
2024-02-09 10:03:05,852 - kedro.io.data_catalog - INFO - Saving data to 'Y_train' (MemoryDataset)...
2024-02-09 10:03:05,861 - kedro.runner.sequential_runner - INFO - Completed 6 out of 8 tasks
2024-02-09 10:03:05,865 - kedro.io.data_catalog - INFO - Loading data from 'val_logger_3_betula_norm' (MemoryDataset)...
2024-02-09 10:03:05,888 - kedro.pipeline.node - INFO - Running node: windowing_val_node: get_windowed_data([val_logger_3_betula_norm]) -> [X_val,Y_val]
2024-02-09 10:03:10,505 - kedro.io.data_catalog - INFO - Saving data to 'X_val' (MemoryDataset)...
2024-02-09 10:03:10,521 - kedro.io.data_catalog - INFO - Saving data to 'Y_val' (MemoryDataset)...
2024-02-09 10:03:10,528 - kedro.runner.sequential_runner - INFO - Completed 7 out of 8 tasks
2024-02-09 10:03:10,535 - kedro.io.data_catalog - INFO - Loading data from 'X_train' (MemoryDataset)...
2024-02-09 10:03:10,535 - kedro.io.data_catalog - INFO - Loading data from 'Y_train' (MemoryDataset)...
2024-02-09 10:03:10,552 - kedro.io.data_catalog - INFO - Loading data from 'X_val' (MemoryDataset)...
2024-02-09 10:03:10,552 - kedro.io.data_catalog - INFO - Loading data from 'Y_val' (MemoryDataset)...
2024-02-09 10:03:10,568 - kedro.io.data_catalog - INFO - Loading data from 'model' (MemoryDataset)...
2024-02-09 10:03:10,569 - kedro.pipeline.node - INFO - Running node: training_node: train_model([X_train,Y_train,X_val,Y_val,model]) -> [trained_model,history]
2024-02-09 10:03:10,569 - kedro.pipeline.node - ERROR - Node 'training_node: train_model([X_train,Y_train,X_val,Y_val,model]) -> [trained_model,history]' failed with error: 
'str' object has no attribute 'fit'
2024-02-09 10:03:10,585 - kedro.runner.sequential_runner - WARNING - There are 1 nodes that have not run.
You can resume the pipeline run from the nearest nodes with persisted inputs by adding the following argument to your previous command:
  --from-nodes "define_model_node,data_cleaning_node"
2024-02-09 10:11:04,442 - kedro.framework.session.session - INFO - Kedro project tentative_agri_proj
2024-02-09 10:11:09,648 - tensorflow - WARNING - From C:\Users\paolo\Documents\GitHub\tentative_agri_proj\.venv\Lib\site-packages\keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

2024-02-09 10:11:10,002 - py.warnings - WARNING - C:\Users\paolo\Documents\GitHub\tentative_agri_proj\.venv\Lib\site-packages\kedro\framework\project\__init__.py:366: UserWarning: An error occurred while importing the 'tentative_agri_proj.pipelines.main_pipeline' module. Nothing defined therein will be returned by 'find_pipelines'.

Traceback (most recent call last):
  File "C:\Users\paolo\Documents\GitHub\tentative_agri_proj\.venv\Lib\site-packages\kedro\framework\project\__init__.py", line 364, in find_pipelines
    pipeline_module = importlib.import_module(pipeline_module_name)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\paolo\AppData\Local\Programs\Python\Python311\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\paolo\Documents\GitHub\tentative_agri_proj\src\tentative_agri_proj\pipelines\main_pipeline\__init__.py", line 1, in <module>
    from .pipeline import create_pipeline  # NOQA
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\paolo\Documents\GitHub\tentative_agri_proj\src\tentative_agri_proj\pipelines\main_pipeline\pipeline.py", line 2, in <module>
    from .nodes import data_cleaning, split_data, normalise_data, define_model, get_windowed_data, train_model, evaluate_model, save_model
ImportError: cannot import name 'save_model' from 'tentative_agri_proj.pipelines.main_pipeline.nodes' (C:\Users\paolo\Documents\GitHub\tentative_agri_proj\src\tentative_agri_proj\pipelines\main_pipeline\nodes.py)

  warnings.warn(

2024-02-09 10:11:27,862 - kedro.framework.session.session - INFO - Kedro project tentative_agri_proj
2024-02-09 10:11:33,281 - tensorflow - WARNING - From C:\Users\paolo\Documents\GitHub\tentative_agri_proj\.venv\Lib\site-packages\keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

2024-02-09 10:11:33,626 - py.warnings - WARNING - C:\Users\paolo\Documents\GitHub\tentative_agri_proj\.venv\Lib\site-packages\kedro\framework\project\__init__.py:366: UserWarning: An error occurred while importing the 'tentative_agri_proj.pipelines.main_pipeline' module. Nothing defined therein will be returned by 'find_pipelines'.

Traceback (most recent call last):
  File "C:\Users\paolo\Documents\GitHub\tentative_agri_proj\.venv\Lib\site-packages\kedro\framework\project\__init__.py", line 364, in find_pipelines
    pipeline_module = importlib.import_module(pipeline_module_name)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\paolo\AppData\Local\Programs\Python\Python311\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\paolo\Documents\GitHub\tentative_agri_proj\src\tentative_agri_proj\pipelines\main_pipeline\__init__.py", line 1, in <module>
    from .pipeline import create_pipeline  # NOQA
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\paolo\Documents\GitHub\tentative_agri_proj\src\tentative_agri_proj\pipelines\main_pipeline\pipeline.py", line 2, in <module>
    from .nodes import data_cleaning, split_data, normalise_data, define_model, get_windowed_data, train_model, evaluate_model, save_model
ImportError: cannot import name 'save_model' from 'tentative_agri_proj.pipelines.main_pipeline.nodes' (C:\Users\paolo\Documents\GitHub\tentative_agri_proj\src\tentative_agri_proj\pipelines\main_pipeline\nodes.py)

  warnings.warn(

2024-02-09 10:12:11,406 - kedro.framework.session.session - INFO - Kedro project tentative_agri_proj
2024-02-09 10:12:16,544 - tensorflow - WARNING - From C:\Users\paolo\Documents\GitHub\tentative_agri_proj\.venv\Lib\site-packages\keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

2024-02-09 10:12:16,873 - py.warnings - WARNING - C:\Users\paolo\Documents\GitHub\tentative_agri_proj\.venv\Lib\site-packages\kedro\framework\project\__init__.py:366: UserWarning: An error occurred while importing the 'tentative_agri_proj.pipelines.main_pipeline' module. Nothing defined therein will be returned by 'find_pipelines'.

Traceback (most recent call last):
  File "C:\Users\paolo\Documents\GitHub\tentative_agri_proj\.venv\Lib\site-packages\kedro\framework\project\__init__.py", line 364, in find_pipelines
    pipeline_module = importlib.import_module(pipeline_module_name)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\paolo\AppData\Local\Programs\Python\Python311\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\paolo\Documents\GitHub\tentative_agri_proj\src\tentative_agri_proj\pipelines\main_pipeline\__init__.py", line 1, in <module>
    from .pipeline import create_pipeline  # NOQA
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\paolo\Documents\GitHub\tentative_agri_proj\src\tentative_agri_proj\pipelines\main_pipeline\pipeline.py", line 2, in <module>
    from .nodes import data_cleaning, split_data, normalise_data, define_model, get_windowed_data, train_model, evaluate_model, save_model
ImportError: cannot import name 'save_model' from 'tentative_agri_proj.pipelines.main_pipeline.nodes' (C:\Users\paolo\Documents\GitHub\tentative_agri_proj\src\tentative_agri_proj\pipelines\main_pipeline\nodes.py)

  warnings.warn(

2024-02-09 10:20:36,879 - kedro.framework.session.session - INFO - Kedro project tentative_agri_proj
2024-02-09 10:20:42,347 - tensorflow - WARNING - From C:\Users\paolo\Documents\GitHub\tentative_agri_proj\.venv\Lib\site-packages\keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

2024-02-09 10:20:42,692 - py.warnings - WARNING - C:\Users\paolo\Documents\GitHub\tentative_agri_proj\.venv\Lib\site-packages\kedro\framework\project\__init__.py:366: UserWarning: An error occurred while importing the 'tentative_agri_proj.pipelines.main_pipeline' module. Nothing defined therein will be returned by 'find_pipelines'.

Traceback (most recent call last):
  File "C:\Users\paolo\Documents\GitHub\tentative_agri_proj\.venv\Lib\site-packages\kedro\framework\project\__init__.py", line 364, in find_pipelines
    pipeline_module = importlib.import_module(pipeline_module_name)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\paolo\AppData\Local\Programs\Python\Python311\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\paolo\Documents\GitHub\tentative_agri_proj\src\tentative_agri_proj\pipelines\main_pipeline\__init__.py", line 1, in <module>
    from .pipeline import create_pipeline  # NOQA
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\paolo\Documents\GitHub\tentative_agri_proj\src\tentative_agri_proj\pipelines\main_pipeline\pipeline.py", line 2, in <module>
    from .nodes import data_cleaning, split_data, normalise_data, define_model, get_windowed_data, train_model, evaluate_model, save_model
ImportError: cannot import name 'save_model' from 'tentative_agri_proj.pipelines.main_pipeline.nodes' (C:\Users\paolo\Documents\GitHub\tentative_agri_proj\src\tentative_agri_proj\pipelines\main_pipeline\nodes.py)

  warnings.warn(

2024-02-09 10:21:16,104 - kedro.framework.session.session - INFO - Kedro project tentative_agri_proj
2024-02-09 10:21:21,305 - tensorflow - WARNING - From C:\Users\paolo\Documents\GitHub\tentative_agri_proj\.venv\Lib\site-packages\keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

2024-02-09 10:21:21,729 - kedro.io.data_catalog - INFO - Loading data from 'logger_3_betula' (CSVDataSet)...
2024-02-09 10:21:21,885 - kedro.pipeline.node - INFO - Running node: data_cleaning_node: data_cleaning([logger_3_betula]) -> [logger_3_betula_cleaned]
2024-02-09 10:21:22,006 - kedro.io.data_catalog - INFO - Saving data to 'logger_3_betula_cleaned' (MemoryDataset)...
2024-02-09 10:21:22,022 - kedro.runner.sequential_runner - INFO - Completed 1 out of 7 tasks
2024-02-09 10:21:22,022 - kedro.pipeline.node - INFO - Running node: define_model_node: define_model(None) -> [model]
2024-02-09 10:21:22,221 - tensorflow - WARNING - From C:\Users\paolo\Documents\GitHub\tentative_agri_proj\.venv\Lib\site-packages\keras\src\utils\tf_utils.py:585: The name tf.executing_eagerly_outside_functions is deprecated. Please use tf.compat.v1.executing_eagerly_outside_functions instead.

2024-02-09 10:21:22,355 - kedro.pipeline.node - ERROR - Node 'define_model_node: define_model(None) -> [model]' failed with error: 
'MyTFModel' object has no attribute 'save_model'
2024-02-09 10:21:22,355 - kedro.runner.sequential_runner - WARNING - There are 6 nodes that have not run.
You can resume the pipeline run from the nearest nodes with persisted inputs by adding the following argument to your previous command:
  --from-nodes "data_cleaning_node"
2024-02-09 10:24:51,835 - kedro.framework.session.session - INFO - Kedro project tentative_agri_proj
2024-02-09 10:24:56,957 - tensorflow - WARNING - From C:\Users\paolo\Documents\GitHub\tentative_agri_proj\.venv\Lib\site-packages\keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

2024-02-09 10:24:57,352 - kedro.io.data_catalog - INFO - Loading data from 'logger_3_betula' (CSVDataSet)...
2024-02-09 10:24:57,536 - kedro.pipeline.node - INFO - Running node: data_cleaning_node: data_cleaning([logger_3_betula]) -> [logger_3_betula_cleaned]
2024-02-09 10:24:57,654 - kedro.io.data_catalog - INFO - Saving data to 'logger_3_betula_cleaned' (MemoryDataset)...
2024-02-09 10:24:57,669 - kedro.runner.sequential_runner - INFO - Completed 1 out of 7 tasks
2024-02-09 10:24:57,669 - kedro.pipeline.node - INFO - Running node: define_model_node: define_model(None) -> [model]
2024-02-09 10:24:57,851 - tensorflow - WARNING - From C:\Users\paolo\Documents\GitHub\tentative_agri_proj\.venv\Lib\site-packages\keras\src\backend.py:873: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

2024-02-09 10:24:58,019 - kedro.pipeline.node - ERROR - Node 'define_model_node: define_model(None) -> [model]' failed with error: 
'Sequential' object has no attribute 'save_model'
2024-02-09 10:24:58,039 - kedro.runner.sequential_runner - WARNING - There are 6 nodes that have not run.
You can resume the pipeline run from the nearest nodes with persisted inputs by adding the following argument to your previous command:
  --from-nodes "data_cleaning_node"
2024-02-09 10:25:28,427 - kedro.framework.session.session - INFO - Kedro project tentative_agri_proj
2024-02-09 10:25:33,747 - tensorflow - WARNING - From C:\Users\paolo\Documents\GitHub\tentative_agri_proj\.venv\Lib\site-packages\keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

2024-02-09 10:25:34,176 - kedro.io.data_catalog - INFO - Loading data from 'logger_3_betula' (CSVDataSet)...
2024-02-09 10:25:34,350 - kedro.pipeline.node - INFO - Running node: data_cleaning_node: data_cleaning([logger_3_betula]) -> [logger_3_betula_cleaned]
2024-02-09 10:25:34,468 - kedro.io.data_catalog - INFO - Saving data to 'logger_3_betula_cleaned' (MemoryDataset)...
2024-02-09 10:25:34,487 - kedro.runner.sequential_runner - INFO - Completed 1 out of 7 tasks
2024-02-09 10:25:34,487 - kedro.pipeline.node - INFO - Running node: define_model_node: define_model(None) -> [model]
2024-02-09 10:25:34,636 - tensorflow - WARNING - From C:\Users\paolo\Documents\GitHub\tentative_agri_proj\.venv\Lib\site-packages\keras\src\backend.py:873: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

2024-02-09 10:25:34,880 - tensorflow - WARNING - From C:\Users\paolo\Documents\GitHub\tentative_agri_proj\.venv\Lib\site-packages\keras\src\saving\legacy\saved_model\save_impl.py:66: The name tf.logging.warning is deprecated. Please use tf.compat.v1.logging.warning instead.

2024-02-09 10:25:34,880 - tensorflow - WARNING - Skipping full serialization of Keras layer <keras.src.engine.sequential.Sequential object at 0x00000222F3D14D90>, because it is not built.
2024-02-09 10:25:34,880 - kedro.pipeline.node - ERROR - Node 'define_model_node: define_model(None) -> [model]' failed with error: 
Model <keras.src.engine.sequential.Sequential object at 0x00000222F3D14D90> cannot be saved because the input shape is not available. Please specify an input shape either by calling `build(input_shape)` directly, or by calling the model on actual data using `Model()`, `Model.fit()`, or `Model.predict()`.
2024-02-09 10:25:34,901 - kedro.runner.sequential_runner - WARNING - There are 6 nodes that have not run.
You can resume the pipeline run from the nearest nodes with persisted inputs by adding the following argument to your previous command:
  --from-nodes "data_cleaning_node"
2024-02-09 10:26:09,634 - kedro.framework.session.session - INFO - Kedro project tentative_agri_proj
2024-02-09 10:26:14,867 - tensorflow - WARNING - From C:\Users\paolo\Documents\GitHub\tentative_agri_proj\.venv\Lib\site-packages\keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

2024-02-09 10:26:15,259 - kedro.io.data_catalog - INFO - Loading data from 'logger_3_betula' (CSVDataSet)...
2024-02-09 10:26:15,426 - kedro.pipeline.node - INFO - Running node: data_cleaning_node: data_cleaning([logger_3_betula]) -> [logger_3_betula_cleaned]
2024-02-09 10:26:15,547 - kedro.io.data_catalog - INFO - Saving data to 'logger_3_betula_cleaned' (MemoryDataset)...
2024-02-09 10:26:15,569 - kedro.runner.sequential_runner - INFO - Completed 1 out of 7 tasks
2024-02-09 10:26:15,572 - kedro.pipeline.node - INFO - Running node: define_model_node: define_model(None) -> [model]
2024-02-09 10:26:15,745 - tensorflow - WARNING - From C:\Users\paolo\Documents\GitHub\tentative_agri_proj\.venv\Lib\site-packages\keras\src\utils\tf_utils.py:585: The name tf.executing_eagerly_outside_functions is deprecated. Please use tf.compat.v1.executing_eagerly_outside_functions instead.

2024-02-09 10:26:15,927 - tensorflow - WARNING - From C:\Users\paolo\Documents\GitHub\tentative_agri_proj\.venv\Lib\site-packages\keras\src\saving\legacy\saved_model\save_impl.py:66: The name tf.logging.warning is deprecated. Please use tf.compat.v1.logging.warning instead.

2024-02-09 10:26:15,927 - tensorflow - WARNING - Skipping full serialization of Keras layer <tentative_agri_proj.pipelines.main_pipeline.nodes.MyTFModel object at 0x000001C3E09B4D90>, because it is not built.
2024-02-09 10:26:15,927 - kedro.pipeline.node - ERROR - Node 'define_model_node: define_model(None) -> [model]' failed with error: 
Model <tentative_agri_proj.pipelines.main_pipeline.nodes.MyTFModel object at 0x000001C3E09B4D90> cannot be saved either because the input shape is not available or because the forward pass of the model is not defined.To define a forward pass, please override `Model.call()`. To specify an input shape, either call `build(input_shape)` directly, or call the model on actual data using `Model()`, `Model.fit()`, or `Model.predict()`. If you have a custom training step, please make sure to invoke the forward pass in train step through `Model.__call__`, i.e. `model(inputs)`, as opposed to `model.call()`.
2024-02-09 10:26:15,951 - kedro.runner.sequential_runner - WARNING - There are 6 nodes that have not run.
You can resume the pipeline run from the nearest nodes with persisted inputs by adding the following argument to your previous command:
  --from-nodes "data_cleaning_node"
2024-02-09 10:27:23,051 - kedro.framework.session.session - INFO - Kedro project tentative_agri_proj
2024-02-09 10:27:28,376 - tensorflow - WARNING - From C:\Users\paolo\Documents\GitHub\tentative_agri_proj\.venv\Lib\site-packages\keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

2024-02-09 10:27:28,808 - kedro.io.data_catalog - INFO - Loading data from 'logger_3_betula' (CSVDataSet)...
2024-02-09 10:27:29,022 - kedro.pipeline.node - INFO - Running node: data_cleaning_node: data_cleaning([logger_3_betula]) -> [logger_3_betula_cleaned]
2024-02-09 10:27:29,167 - kedro.io.data_catalog - INFO - Saving data to 'logger_3_betula_cleaned' (MemoryDataset)...
2024-02-09 10:27:29,180 - kedro.runner.sequential_runner - INFO - Completed 1 out of 7 tasks
2024-02-09 10:27:29,183 - kedro.pipeline.node - INFO - Running node: define_model_node: define_model(None) -> [model]
2024-02-09 10:27:29,365 - tensorflow - WARNING - From C:\Users\paolo\Documents\GitHub\tentative_agri_proj\.venv\Lib\site-packages\keras\src\utils\tf_utils.py:585: The name tf.executing_eagerly_outside_functions is deprecated. Please use tf.compat.v1.executing_eagerly_outside_functions instead.

2024-02-09 10:27:29,504 - kedro.pipeline.node - ERROR - Node 'define_model_node: define_model(None) -> [model]' failed with error: 
Model.export() got an unexpected keyword argument 'overwrite'
2024-02-09 10:27:29,508 - kedro.runner.sequential_runner - WARNING - There are 6 nodes that have not run.
You can resume the pipeline run from the nearest nodes with persisted inputs by adding the following argument to your previous command:
  --from-nodes "data_cleaning_node"
2024-02-09 10:27:40,610 - kedro.framework.session.session - INFO - Kedro project tentative_agri_proj
2024-02-09 10:27:46,911 - tensorflow - WARNING - From C:\Users\paolo\Documents\GitHub\tentative_agri_proj\.venv\Lib\site-packages\keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

2024-02-09 10:27:47,344 - kedro.io.data_catalog - INFO - Loading data from 'logger_3_betula' (CSVDataSet)...
2024-02-09 10:27:47,508 - kedro.pipeline.node - INFO - Running node: data_cleaning_node: data_cleaning([logger_3_betula]) -> [logger_3_betula_cleaned]
2024-02-09 10:27:47,644 - kedro.io.data_catalog - INFO - Saving data to 'logger_3_betula_cleaned' (MemoryDataset)...
2024-02-09 10:27:47,660 - kedro.runner.sequential_runner - INFO - Completed 1 out of 7 tasks
2024-02-09 10:27:47,660 - kedro.pipeline.node - INFO - Running node: define_model_node: define_model(None) -> [model]
2024-02-09 10:27:47,907 - tensorflow - WARNING - From C:\Users\paolo\Documents\GitHub\tentative_agri_proj\.venv\Lib\site-packages\keras\src\utils\tf_utils.py:585: The name tf.executing_eagerly_outside_functions is deprecated. Please use tf.compat.v1.executing_eagerly_outside_functions instead.

2024-02-09 10:27:48,045 - kedro.pipeline.node - ERROR - Node 'define_model_node: define_model(None) -> [model]' failed with error: 
The layer provided has not yet been built. It must be built before export.
2024-02-09 10:27:48,061 - kedro.runner.sequential_runner - WARNING - There are 6 nodes that have not run.
You can resume the pipeline run from the nearest nodes with persisted inputs by adding the following argument to your previous command:
  --from-nodes "data_cleaning_node"
2024-02-09 10:31:03,561 - kedro.framework.session.session - INFO - Kedro project tentative_agri_proj
2024-02-09 10:31:09,368 - tensorflow - WARNING - From C:\Users\paolo\Documents\GitHub\tentative_agri_proj\.venv\Lib\site-packages\keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

2024-02-09 10:31:09,794 - kedro.io.data_catalog - INFO - Loading data from 'logger_3_betula' (CSVDataSet)...
2024-02-09 10:31:09,963 - kedro.pipeline.node - INFO - Running node: data_cleaning_node: data_cleaning([logger_3_betula]) -> [logger_3_betula_cleaned]
2024-02-09 10:31:10,094 - kedro.io.data_catalog - INFO - Saving data to 'logger_3_betula_cleaned' (MemoryDataset)...
2024-02-09 10:31:10,113 - kedro.runner.sequential_runner - INFO - Completed 1 out of 7 tasks
2024-02-09 10:31:10,113 - kedro.pipeline.node - INFO - Running node: define_model_node: define_model(None) -> [model]
2024-02-09 10:31:10,295 - tensorflow - WARNING - From C:\Users\paolo\Documents\GitHub\tentative_agri_proj\.venv\Lib\site-packages\keras\src\utils\tf_utils.py:585: The name tf.executing_eagerly_outside_functions is deprecated. Please use tf.compat.v1.executing_eagerly_outside_functions instead.

2024-02-09 10:31:10,495 - tensorflow - WARNING - From C:\Users\paolo\Documents\GitHub\tentative_agri_proj\.venv\Lib\site-packages\keras\src\engine\base_layer_utils.py:189: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

2024-02-09 10:31:10,912 - kedro.pipeline.node - ERROR - Node 'define_model_node: define_model(None) -> [model]' failed with error: 
Model <tentative_agri_proj.pipelines.main_pipeline.nodes.MyTFModel object at 0x000001FC8EAACE90> cannot be saved either because the input shape is not available or because the forward pass of the model is not defined.To define a forward pass, please override `Model.call()`. To specify an input shape, either call `build(input_shape)` directly, or call the model on actual data using `Model()`, `Model.fit()`, or `Model.predict()`. If you have a custom training step, please make sure to invoke the forward pass in train step through `Model.__call__`, i.e. `model(inputs)`, as opposed to `model.call()`.
2024-02-09 10:31:10,927 - kedro.runner.sequential_runner - WARNING - There are 6 nodes that have not run.
You can resume the pipeline run from the nearest nodes with persisted inputs by adding the following argument to your previous command:
  --from-nodes "data_cleaning_node"
2024-02-09 10:32:32,305 - kedro.framework.session.session - INFO - Kedro project tentative_agri_proj
2024-02-09 10:32:37,546 - tensorflow - WARNING - From C:\Users\paolo\Documents\GitHub\tentative_agri_proj\.venv\Lib\site-packages\keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

2024-02-09 10:32:38,000 - kedro.io.data_catalog - INFO - Loading data from 'logger_3_betula' (CSVDataSet)...
2024-02-09 10:32:38,168 - kedro.pipeline.node - INFO - Running node: data_cleaning_node: data_cleaning([logger_3_betula]) -> [logger_3_betula_cleaned]
2024-02-09 10:32:38,303 - kedro.io.data_catalog - INFO - Saving data to 'logger_3_betula_cleaned' (MemoryDataset)...
2024-02-09 10:32:38,303 - kedro.runner.sequential_runner - INFO - Completed 1 out of 7 tasks
2024-02-09 10:32:38,319 - kedro.pipeline.node - INFO - Running node: define_model_node: define_model(None) -> [model]
2024-02-09 10:32:38,470 - tensorflow - WARNING - From C:\Users\paolo\Documents\GitHub\tentative_agri_proj\.venv\Lib\site-packages\keras\src\backend.py:873: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

2024-02-09 10:32:41,948 - kedro.io.data_catalog - INFO - Saving data to 'model' (MemoryDataset)...
2024-02-09 10:32:41,948 - kedro.runner.sequential_runner - INFO - Completed 2 out of 7 tasks
2024-02-09 10:32:41,948 - kedro.io.data_catalog - INFO - Loading data from 'logger_3_betula_cleaned' (MemoryDataset)...
2024-02-09 10:32:41,972 - kedro.pipeline.node - INFO - Running node: split_data_node: split_data([logger_3_betula_cleaned]) -> [train_logger_3_betula,val_logger_3_betula,test_logger_3_betula]
2024-02-09 10:32:42,020 - kedro.io.data_catalog - INFO - Saving data to 'train_logger_3_betula' (MemoryDataset)...
2024-02-09 10:32:42,048 - kedro.io.data_catalog - INFO - Saving data to 'val_logger_3_betula' (MemoryDataset)...
2024-02-09 10:32:42,065 - kedro.io.data_catalog - INFO - Saving data to 'test_logger_3_betula' (MemoryDataset)...
2024-02-09 10:32:42,070 - kedro.runner.sequential_runner - INFO - Completed 3 out of 7 tasks
2024-02-09 10:32:42,070 - kedro.io.data_catalog - INFO - Loading data from 'train_logger_3_betula' (MemoryDataset)...
2024-02-09 10:32:42,088 - kedro.io.data_catalog - INFO - Loading data from 'val_logger_3_betula' (MemoryDataset)...
2024-02-09 10:32:42,105 - kedro.io.data_catalog - INFO - Loading data from 'test_logger_3_betula' (MemoryDataset)...
2024-02-09 10:32:42,153 - kedro.pipeline.node - INFO - Running node: normalise_data_node: normalise_data([train_logger_3_betula,val_logger_3_betula,test_logger_3_betula]) -> [train_logger_3_betula_norm,val_logger_3_betula_norm,test_logger_3_betula_norm]
2024-02-09 10:32:42,251 - kedro.io.data_catalog - INFO - Saving data to 'train_logger_3_betula_norm' (MemoryDataset)...
2024-02-09 10:32:42,286 - kedro.io.data_catalog - INFO - Saving data to 'val_logger_3_betula_norm' (MemoryDataset)...
2024-02-09 10:32:42,305 - kedro.io.data_catalog - INFO - Saving data to 'test_logger_3_betula_norm' (MemoryDataset)...
2024-02-09 10:32:42,374 - kedro.runner.sequential_runner - INFO - Completed 4 out of 7 tasks
2024-02-09 10:32:42,385 - kedro.io.data_catalog - INFO - Loading data from 'test_logger_3_betula_norm' (MemoryDataset)...
2024-02-09 10:32:42,419 - kedro.pipeline.node - INFO - Running node: windowing_test_node: get_windowed_data([test_logger_3_betula_norm]) -> [X_test,Y_test]
2024-02-09 10:32:45,038 - kedro.io.data_catalog - INFO - Saving data to 'X_test' (MemoryDataset)...
2024-02-09 10:32:45,048 - kedro.io.data_catalog - INFO - Saving data to 'Y_test' (MemoryDataset)...
2024-02-09 10:32:45,055 - kedro.runner.sequential_runner - INFO - Completed 5 out of 7 tasks
2024-02-09 10:32:45,056 - kedro.io.data_catalog - INFO - Loading data from 'train_logger_3_betula_norm' (MemoryDataset)...
2024-02-09 10:32:45,083 - kedro.pipeline.node - INFO - Running node: windowing_train_node: get_windowed_data([train_logger_3_betula_norm]) -> [X_train,Y_train]
2024-02-09 10:33:03,365 - kedro.io.data_catalog - INFO - Saving data to 'X_train' (MemoryDataset)...
2024-02-09 10:33:03,380 - kedro.io.data_catalog - INFO - Saving data to 'Y_train' (MemoryDataset)...
2024-02-09 10:33:03,402 - kedro.runner.sequential_runner - INFO - Completed 6 out of 7 tasks
2024-02-09 10:33:03,405 - kedro.io.data_catalog - INFO - Loading data from 'val_logger_3_betula_norm' (MemoryDataset)...
2024-02-09 10:33:03,415 - kedro.pipeline.node - INFO - Running node: windowing_val_node: get_windowed_data([val_logger_3_betula_norm]) -> [X_val,Y_val]
2024-02-09 10:33:08,573 - kedro.io.data_catalog - INFO - Saving data to 'X_val' (MemoryDataset)...
2024-02-09 10:33:08,574 - kedro.io.data_catalog - INFO - Saving data to 'Y_val' (MemoryDataset)...
2024-02-09 10:33:08,586 - kedro.runner.sequential_runner - INFO - Completed 7 out of 7 tasks
2024-02-09 10:33:08,586 - kedro.runner.sequential_runner - INFO - Pipeline execution completed successfully.
2024-02-09 10:33:08,596 - kedro.io.data_catalog - INFO - Loading data from 'Y_train' (MemoryDataset)...
2024-02-09 10:33:08,596 - kedro.io.data_catalog - INFO - Loading data from 'Y_test' (MemoryDataset)...
2024-02-09 10:33:08,596 - kedro.io.data_catalog - INFO - Loading data from 'X_test' (MemoryDataset)...
2024-02-09 10:33:08,596 - kedro.io.data_catalog - INFO - Loading data from 'Y_val' (MemoryDataset)...
2024-02-09 10:33:08,613 - kedro.io.data_catalog - INFO - Loading data from 'X_val' (MemoryDataset)...
2024-02-09 10:33:08,613 - kedro.io.data_catalog - INFO - Loading data from 'model' (MemoryDataset)...
2024-02-09 10:33:08,613 - kedro.io.data_catalog - INFO - Loading data from 'X_train' (MemoryDataset)...
2024-02-09 10:34:26,781 - kedro.framework.session.session - INFO - Kedro project tentative_agri_proj
2024-02-09 10:34:33,466 - tensorflow - WARNING - From C:\Users\paolo\Documents\GitHub\tentative_agri_proj\.venv\Lib\site-packages\keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

2024-02-09 10:34:34,130 - kedro.io.data_catalog - INFO - Loading data from 'logger_3_betula' (CSVDataSet)...
2024-02-09 10:34:34,422 - kedro.pipeline.node - INFO - Running node: data_cleaning_node: data_cleaning([logger_3_betula]) -> [logger_3_betula_cleaned]
2024-02-09 10:34:34,625 - kedro.io.data_catalog - INFO - Saving data to 'logger_3_betula_cleaned' (MemoryDataset)...
2024-02-09 10:34:34,645 - kedro.runner.sequential_runner - INFO - Completed 1 out of 8 tasks
2024-02-09 10:34:34,651 - kedro.pipeline.node - INFO - Running node: define_model_node: define_model(None) -> [model]
2024-02-09 10:34:35,351 - tensorflow - WARNING - From C:\Users\paolo\Documents\GitHub\tentative_agri_proj\.venv\Lib\site-packages\keras\src\backend.py:873: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

2024-02-09 10:34:46,285 - kedro.io.data_catalog - INFO - Saving data to 'model' (MemoryDataset)...
2024-02-09 10:34:46,328 - kedro.runner.sequential_runner - INFO - Completed 2 out of 8 tasks
2024-02-09 10:34:46,358 - kedro.io.data_catalog - INFO - Loading data from 'logger_3_betula_cleaned' (MemoryDataset)...
2024-02-09 10:34:46,391 - kedro.pipeline.node - INFO - Running node: split_data_node: split_data([logger_3_betula_cleaned]) -> [train_logger_3_betula,val_logger_3_betula,test_logger_3_betula]
2024-02-09 10:34:46,456 - kedro.io.data_catalog - INFO - Saving data to 'train_logger_3_betula' (MemoryDataset)...
2024-02-09 10:34:46,498 - kedro.io.data_catalog - INFO - Saving data to 'val_logger_3_betula' (MemoryDataset)...
2024-02-09 10:34:46,523 - kedro.io.data_catalog - INFO - Saving data to 'test_logger_3_betula' (MemoryDataset)...
2024-02-09 10:34:46,544 - kedro.runner.sequential_runner - INFO - Completed 3 out of 8 tasks
2024-02-09 10:34:46,554 - kedro.io.data_catalog - INFO - Loading data from 'train_logger_3_betula' (MemoryDataset)...
2024-02-09 10:34:46,587 - kedro.io.data_catalog - INFO - Loading data from 'val_logger_3_betula' (MemoryDataset)...
2024-02-09 10:34:46,615 - kedro.io.data_catalog - INFO - Loading data from 'test_logger_3_betula' (MemoryDataset)...
2024-02-09 10:34:46,714 - kedro.pipeline.node - INFO - Running node: normalise_data_node: normalise_data([train_logger_3_betula,val_logger_3_betula,test_logger_3_betula]) -> [train_logger_3_betula_norm,val_logger_3_betula_norm,test_logger_3_betula_norm]
2024-02-09 10:34:46,831 - kedro.io.data_catalog - INFO - Saving data to 'train_logger_3_betula_norm' (MemoryDataset)...
2024-02-09 10:34:46,865 - kedro.io.data_catalog - INFO - Saving data to 'val_logger_3_betula_norm' (MemoryDataset)...
2024-02-09 10:34:46,936 - kedro.io.data_catalog - INFO - Saving data to 'test_logger_3_betula_norm' (MemoryDataset)...
2024-02-09 10:34:46,957 - kedro.runner.sequential_runner - INFO - Completed 4 out of 8 tasks
2024-02-09 10:34:46,960 - kedro.io.data_catalog - INFO - Loading data from 'test_logger_3_betula_norm' (MemoryDataset)...
2024-02-09 10:34:47,009 - kedro.pipeline.node - INFO - Running node: windowing_test_node: get_windowed_data([test_logger_3_betula_norm]) -> [X_test,Y_test]
2024-02-09 10:34:52,762 - kedro.io.data_catalog - INFO - Saving data to 'X_test' (MemoryDataset)...
2024-02-09 10:34:52,762 - kedro.io.data_catalog - INFO - Saving data to 'Y_test' (MemoryDataset)...
2024-02-09 10:34:52,782 - kedro.runner.sequential_runner - INFO - Completed 5 out of 8 tasks
2024-02-09 10:34:52,784 - kedro.io.data_catalog - INFO - Loading data from 'train_logger_3_betula_norm' (MemoryDataset)...
2024-02-09 10:34:52,818 - kedro.pipeline.node - INFO - Running node: windowing_train_node: get_windowed_data([train_logger_3_betula_norm]) -> [X_train,Y_train]
2024-02-09 10:35:14,338 - kedro.io.data_catalog - INFO - Saving data to 'X_train' (MemoryDataset)...
2024-02-09 10:35:14,359 - kedro.io.data_catalog - INFO - Saving data to 'Y_train' (MemoryDataset)...
2024-02-09 10:35:14,359 - kedro.runner.sequential_runner - INFO - Completed 6 out of 8 tasks
2024-02-09 10:35:14,359 - kedro.io.data_catalog - INFO - Loading data from 'val_logger_3_betula_norm' (MemoryDataset)...
2024-02-09 10:35:14,392 - kedro.pipeline.node - INFO - Running node: windowing_val_node: get_windowed_data([val_logger_3_betula_norm]) -> [X_val,Y_val]
2024-02-09 10:35:19,554 - kedro.io.data_catalog - INFO - Saving data to 'X_val' (MemoryDataset)...
2024-02-09 10:35:19,554 - kedro.io.data_catalog - INFO - Saving data to 'Y_val' (MemoryDataset)...
2024-02-09 10:35:19,569 - kedro.runner.sequential_runner - INFO - Completed 7 out of 8 tasks
2024-02-09 10:35:19,572 - kedro.io.data_catalog - INFO - Loading data from 'X_train' (MemoryDataset)...
2024-02-09 10:35:19,592 - kedro.io.data_catalog - INFO - Loading data from 'Y_train' (MemoryDataset)...
2024-02-09 10:35:19,593 - kedro.io.data_catalog - INFO - Loading data from 'X_val' (MemoryDataset)...
2024-02-09 10:35:19,607 - kedro.io.data_catalog - INFO - Loading data from 'Y_val' (MemoryDataset)...
2024-02-09 10:35:19,608 - kedro.io.data_catalog - INFO - Loading data from 'model' (MemoryDataset)...
2024-02-09 10:35:19,608 - kedro.pipeline.node - INFO - Running node: training_node: train_model([X_train,Y_train,X_val,Y_val,model]) -> [history]
2024-02-09 10:35:19,705 - tensorflow - WARNING - From C:\Users\paolo\Documents\GitHub\tentative_agri_proj\.venv\Lib\site-packages\keras\src\saving\legacy\saved_model\load.py:107: The name tf.gfile.Exists is deprecated. Please use tf.io.gfile.exists instead.

2024-02-09 10:35:21,646 - tensorflow - WARNING - From C:\Users\paolo\Documents\GitHub\tentative_agri_proj\.venv\Lib\site-packages\keras\src\utils\tf_utils.py:492: The name tf.ragged.RaggedTensorValue is deprecated. Please use tf.compat.v1.ragged.RaggedTensorValue instead.

2024-02-09 10:39:33,234 - kedro.pipeline.node - ERROR - Node 'training_node: train_model([X_train,Y_train,X_val,Y_val,model]) -> [history]' failed with error: 
'Sequential' object has no attribute 'save_model'
2024-02-09 10:39:33,243 - kedro.runner.sequential_runner - WARNING - There are 1 nodes that have not run.
You can resume the pipeline run from the nearest nodes with persisted inputs by adding the following argument to your previous command:
  --from-nodes "data_cleaning_node,define_model_node"
2024-02-09 10:43:39,047 - kedro.framework.session.session - INFO - Kedro project tentative_agri_proj
2024-02-09 10:43:45,687 - tensorflow - WARNING - From C:\Users\paolo\Documents\GitHub\tentative_agri_proj\.venv\Lib\site-packages\keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

2024-02-09 10:43:46,289 - kedro.io.data_catalog - INFO - Loading data from 'logger_3_betula' (CSVDataSet)...
2024-02-09 10:43:46,473 - kedro.pipeline.node - INFO - Running node: data_cleaning_node: data_cleaning([logger_3_betula]) -> [logger_3_betula_cleaned]
2024-02-09 10:43:46,589 - kedro.io.data_catalog - INFO - Saving data to 'logger_3_betula_cleaned' (MemoryDataset)...
2024-02-09 10:43:46,605 - kedro.runner.sequential_runner - INFO - Completed 1 out of 9 tasks
2024-02-09 10:43:46,617 - kedro.pipeline.node - INFO - Running node: define_model_node: define_model(None) -> [model]
2024-02-09 10:43:46,773 - tensorflow - WARNING - From C:\Users\paolo\Documents\GitHub\tentative_agri_proj\.venv\Lib\site-packages\keras\src\backend.py:873: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

2024-02-09 10:43:50,329 - kedro.io.data_catalog - INFO - Saving data to 'model' (MemoryDataset)...
2024-02-09 10:43:50,345 - kedro.runner.sequential_runner - INFO - Completed 2 out of 9 tasks
2024-02-09 10:43:50,345 - kedro.io.data_catalog - INFO - Loading data from 'logger_3_betula_cleaned' (MemoryDataset)...
2024-02-09 10:43:50,374 - kedro.pipeline.node - INFO - Running node: split_data_node: split_data([logger_3_betula_cleaned]) -> [train_logger_3_betula,val_logger_3_betula,test_logger_3_betula]
2024-02-09 10:43:50,410 - kedro.io.data_catalog - INFO - Saving data to 'train_logger_3_betula' (MemoryDataset)...
2024-02-09 10:43:50,445 - kedro.io.data_catalog - INFO - Saving data to 'val_logger_3_betula' (MemoryDataset)...
2024-02-09 10:43:50,459 - kedro.io.data_catalog - INFO - Saving data to 'test_logger_3_betula' (MemoryDataset)...
2024-02-09 10:43:50,482 - kedro.runner.sequential_runner - INFO - Completed 3 out of 9 tasks
2024-02-09 10:43:50,482 - kedro.io.data_catalog - INFO - Loading data from 'train_logger_3_betula' (MemoryDataset)...
2024-02-09 10:43:50,493 - kedro.io.data_catalog - INFO - Loading data from 'val_logger_3_betula' (MemoryDataset)...
2024-02-09 10:43:50,510 - kedro.io.data_catalog - INFO - Loading data from 'test_logger_3_betula' (MemoryDataset)...
2024-02-09 10:43:50,560 - kedro.pipeline.node - INFO - Running node: normalise_data_node: normalise_data([train_logger_3_betula,val_logger_3_betula,test_logger_3_betula]) -> [train_logger_3_betula_norm,val_logger_3_betula_norm,test_logger_3_betula_norm]
2024-02-09 10:43:50,633 - kedro.io.data_catalog - INFO - Saving data to 'train_logger_3_betula_norm' (MemoryDataset)...
2024-02-09 10:43:50,650 - kedro.io.data_catalog - INFO - Saving data to 'val_logger_3_betula_norm' (MemoryDataset)...
2024-02-09 10:43:50,658 - kedro.io.data_catalog - INFO - Saving data to 'test_logger_3_betula_norm' (MemoryDataset)...
2024-02-09 10:43:50,682 - kedro.runner.sequential_runner - INFO - Completed 4 out of 9 tasks
2024-02-09 10:43:50,682 - kedro.io.data_catalog - INFO - Loading data from 'test_logger_3_betula_norm' (MemoryDataset)...
2024-02-09 10:43:50,693 - kedro.pipeline.node - INFO - Running node: windowing_test_node: get_windowed_data([test_logger_3_betula_norm]) -> [X_test,Y_test]
2024-02-09 10:43:53,146 - kedro.io.data_catalog - INFO - Saving data to 'X_test' (MemoryDataset)...
2024-02-09 10:43:53,148 - kedro.io.data_catalog - INFO - Saving data to 'Y_test' (MemoryDataset)...
2024-02-09 10:43:53,159 - kedro.runner.sequential_runner - INFO - Completed 5 out of 9 tasks
2024-02-09 10:43:53,168 - kedro.io.data_catalog - INFO - Loading data from 'train_logger_3_betula_norm' (MemoryDataset)...
2024-02-09 10:43:53,209 - kedro.pipeline.node - INFO - Running node: windowing_train_node: get_windowed_data([train_logger_3_betula_norm]) -> [X_train,Y_train]
2024-02-09 10:44:09,690 - kedro.io.data_catalog - INFO - Saving data to 'X_train' (MemoryDataset)...
2024-02-09 10:44:09,720 - kedro.io.data_catalog - INFO - Saving data to 'Y_train' (MemoryDataset)...
2024-02-09 10:44:09,722 - kedro.runner.sequential_runner - INFO - Completed 6 out of 9 tasks
2024-02-09 10:44:09,722 - kedro.io.data_catalog - INFO - Loading data from 'val_logger_3_betula_norm' (MemoryDataset)...
2024-02-09 10:44:09,740 - kedro.pipeline.node - INFO - Running node: windowing_val_node: get_windowed_data([val_logger_3_betula_norm]) -> [X_val,Y_val]
2024-02-09 10:44:14,657 - kedro.io.data_catalog - INFO - Saving data to 'X_val' (MemoryDataset)...
2024-02-09 10:44:14,657 - kedro.io.data_catalog - INFO - Saving data to 'Y_val' (MemoryDataset)...
2024-02-09 10:44:14,675 - kedro.runner.sequential_runner - INFO - Completed 7 out of 9 tasks
2024-02-09 10:44:14,675 - kedro.io.data_catalog - INFO - Loading data from 'X_test' (MemoryDataset)...
2024-02-09 10:44:14,687 - kedro.io.data_catalog - INFO - Loading data from 'Y_test' (MemoryDataset)...
2024-02-09 10:44:14,687 - kedro.pipeline.node - INFO - Running node: eval_node: evaluate_model([X_test,Y_test]) -> [evaluation]
2024-02-09 10:44:14,687 - kedro.pipeline.node - ERROR - Node 'eval_node: evaluate_model([X_test,Y_test]) -> [evaluation]' failed with error: 
No file or directory found at data/06_models/tensorflow_lstm_trained
2024-02-09 10:44:14,703 - kedro.runner.sequential_runner - WARNING - There are 2 nodes that have not run.
You can resume the pipeline run from the nearest nodes with persisted inputs by adding the following argument to your previous command:
  --from-nodes "define_model_node,data_cleaning_node"
2024-02-09 10:46:44,232 - kedro.framework.session.session - INFO - Kedro project tentative_agri_proj
2024-02-09 10:46:49,275 - tensorflow - WARNING - From C:\Users\paolo\Documents\GitHub\tentative_agri_proj\.venv\Lib\site-packages\keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

2024-02-09 10:46:49,668 - kedro.io.data_catalog - INFO - Loading data from 'logger_3_betula' (CSVDataSet)...
2024-02-09 10:46:49,836 - kedro.pipeline.node - INFO - Running node: data_cleaning_node: data_cleaning([logger_3_betula]) -> [logger_3_betula_cleaned]
2024-02-09 10:46:49,971 - kedro.io.data_catalog - INFO - Saving data to 'logger_3_betula_cleaned' (MemoryDataset)...
2024-02-09 10:46:49,971 - kedro.runner.sequential_runner - INFO - Completed 1 out of 9 tasks
2024-02-09 10:46:49,987 - kedro.pipeline.node - INFO - Running node: define_model_node: define_model(None) -> [model]
2024-02-09 10:46:50,138 - tensorflow - WARNING - From C:\Users\paolo\Documents\GitHub\tentative_agri_proj\.venv\Lib\site-packages\keras\src\backend.py:873: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

2024-02-09 10:46:53,601 - kedro.io.data_catalog - INFO - Saving data to 'model' (MemoryDataset)...
2024-02-09 10:46:53,617 - kedro.runner.sequential_runner - INFO - Completed 2 out of 9 tasks
2024-02-09 10:46:53,617 - kedro.io.data_catalog - INFO - Loading data from 'logger_3_betula_cleaned' (MemoryDataset)...
2024-02-09 10:46:53,653 - kedro.pipeline.node - INFO - Running node: split_data_node: split_data([logger_3_betula_cleaned]) -> [train_logger_3_betula,val_logger_3_betula,test_logger_3_betula]
2024-02-09 10:46:53,704 - kedro.io.data_catalog - INFO - Saving data to 'train_logger_3_betula' (MemoryDataset)...
2024-02-09 10:46:53,723 - kedro.io.data_catalog - INFO - Saving data to 'val_logger_3_betula' (MemoryDataset)...
2024-02-09 10:46:53,737 - kedro.io.data_catalog - INFO - Saving data to 'test_logger_3_betula' (MemoryDataset)...
2024-02-09 10:46:53,755 - kedro.runner.sequential_runner - INFO - Completed 3 out of 9 tasks
2024-02-09 10:46:53,755 - kedro.io.data_catalog - INFO - Loading data from 'train_logger_3_betula' (MemoryDataset)...
2024-02-09 10:46:53,771 - kedro.io.data_catalog - INFO - Loading data from 'val_logger_3_betula' (MemoryDataset)...
2024-02-09 10:46:53,788 - kedro.io.data_catalog - INFO - Loading data from 'test_logger_3_betula' (MemoryDataset)...
2024-02-09 10:46:53,820 - kedro.pipeline.node - INFO - Running node: normalise_data_node: normalise_data([train_logger_3_betula,val_logger_3_betula,test_logger_3_betula]) -> [train_logger_3_betula_norm,val_logger_3_betula_norm,test_logger_3_betula_norm]
2024-02-09 10:46:53,906 - kedro.io.data_catalog - INFO - Saving data to 'train_logger_3_betula_norm' (MemoryDataset)...
2024-02-09 10:46:53,925 - kedro.io.data_catalog - INFO - Saving data to 'val_logger_3_betula_norm' (MemoryDataset)...
2024-02-09 10:46:53,936 - kedro.io.data_catalog - INFO - Saving data to 'test_logger_3_betula_norm' (MemoryDataset)...
2024-02-09 10:46:53,954 - kedro.runner.sequential_runner - INFO - Completed 4 out of 9 tasks
2024-02-09 10:46:53,954 - kedro.io.data_catalog - INFO - Loading data from 'test_logger_3_betula_norm' (MemoryDataset)...
2024-02-09 10:46:53,971 - kedro.pipeline.node - INFO - Running node: windowing_test_node: get_windowed_data([test_logger_3_betula_norm]) -> [X_test,Y_test]
2024-02-09 10:46:56,374 - kedro.io.data_catalog - INFO - Saving data to 'X_test' (MemoryDataset)...
2024-02-09 10:46:56,389 - kedro.io.data_catalog - INFO - Saving data to 'Y_test' (MemoryDataset)...
2024-02-09 10:46:56,393 - kedro.runner.sequential_runner - INFO - Completed 5 out of 9 tasks
2024-02-09 10:46:56,400 - kedro.io.data_catalog - INFO - Loading data from 'train_logger_3_betula_norm' (MemoryDataset)...
2024-02-09 10:46:56,419 - kedro.pipeline.node - INFO - Running node: windowing_train_node: get_windowed_data([train_logger_3_betula_norm]) -> [X_train,Y_train]
2024-02-09 10:47:13,231 - kedro.io.data_catalog - INFO - Saving data to 'X_train' (MemoryDataset)...
2024-02-09 10:47:13,250 - kedro.io.data_catalog - INFO - Saving data to 'Y_train' (MemoryDataset)...
2024-02-09 10:47:13,250 - kedro.runner.sequential_runner - INFO - Completed 6 out of 9 tasks
2024-02-09 10:47:13,267 - kedro.io.data_catalog - INFO - Loading data from 'val_logger_3_betula_norm' (MemoryDataset)...
2024-02-09 10:47:13,286 - kedro.pipeline.node - INFO - Running node: windowing_val_node: get_windowed_data([val_logger_3_betula_norm]) -> [X_val,Y_val]
2024-02-09 10:47:18,275 - kedro.io.data_catalog - INFO - Saving data to 'X_val' (MemoryDataset)...
2024-02-09 10:47:18,275 - kedro.io.data_catalog - INFO - Saving data to 'Y_val' (MemoryDataset)...
2024-02-09 10:47:18,289 - kedro.runner.sequential_runner - INFO - Completed 7 out of 9 tasks
2024-02-09 10:47:18,289 - kedro.io.data_catalog - INFO - Loading data from 'X_test' (MemoryDataset)...
2024-02-09 10:47:18,297 - kedro.io.data_catalog - INFO - Loading data from 'Y_test' (MemoryDataset)...
2024-02-09 10:47:18,297 - kedro.pipeline.node - INFO - Running node: eval_node: evaluate_model([X_test,Y_test]) -> [evaluation]
2024-02-09 10:47:18,297 - kedro.pipeline.node - ERROR - Node 'eval_node: evaluate_model([X_test,Y_test]) -> [evaluation]' failed with error: 
No file or directory found at data/06_models/tensorflow_lstm_trained
2024-02-09 10:47:18,315 - kedro.runner.sequential_runner - WARNING - There are 2 nodes that have not run.
You can resume the pipeline run from the nearest nodes with persisted inputs by adding the following argument to your previous command:
  --from-nodes "define_model_node,data_cleaning_node"
2024-02-09 10:50:41,228 - kedro.framework.session.session - INFO - Kedro project tentative_agri_proj
2024-02-09 10:50:47,432 - tensorflow - WARNING - From C:\Users\paolo\Documents\GitHub\tentative_agri_proj\.venv\Lib\site-packages\keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

2024-02-09 10:50:47,850 - kedro.io.data_catalog - INFO - Loading data from 'logger_3_betula' (CSVDataSet)...
2024-02-09 10:50:48,029 - kedro.pipeline.node - INFO - Running node: data_cleaning_node: data_cleaning([logger_3_betula]) -> [logger_3_betula_cleaned]
2024-02-09 10:50:48,147 - kedro.io.data_catalog - INFO - Saving data to 'logger_3_betula_cleaned' (MemoryDataset)...
2024-02-09 10:50:48,172 - kedro.runner.sequential_runner - INFO - Completed 1 out of 9 tasks
2024-02-09 10:50:48,179 - kedro.pipeline.node - INFO - Running node: define_model_node: define_model(None) -> [model]
2024-02-09 10:50:48,345 - tensorflow - WARNING - From C:\Users\paolo\Documents\GitHub\tentative_agri_proj\.venv\Lib\site-packages\keras\src\backend.py:873: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

2024-02-09 10:50:52,545 - kedro.io.data_catalog - INFO - Saving data to 'model' (MemoryDataset)...
2024-02-09 10:50:52,548 - kedro.runner.sequential_runner - INFO - Completed 2 out of 9 tasks
2024-02-09 10:50:52,551 - kedro.io.data_catalog - INFO - Loading data from 'logger_3_betula_cleaned' (MemoryDataset)...
2024-02-09 10:50:52,562 - kedro.pipeline.node - INFO - Running node: split_data_node: split_data([logger_3_betula_cleaned]) -> [train_logger_3_betula,val_logger_3_betula,test_logger_3_betula]
2024-02-09 10:50:52,613 - kedro.io.data_catalog - INFO - Saving data to 'train_logger_3_betula' (MemoryDataset)...
2024-02-09 10:50:52,646 - kedro.io.data_catalog - INFO - Saving data to 'val_logger_3_betula' (MemoryDataset)...
2024-02-09 10:50:52,662 - kedro.io.data_catalog - INFO - Saving data to 'test_logger_3_betula' (MemoryDataset)...
2024-02-09 10:50:52,680 - kedro.runner.sequential_runner - INFO - Completed 3 out of 9 tasks
2024-02-09 10:50:52,680 - kedro.io.data_catalog - INFO - Loading data from 'train_logger_3_betula' (MemoryDataset)...
2024-02-09 10:50:52,697 - kedro.io.data_catalog - INFO - Loading data from 'val_logger_3_betula' (MemoryDataset)...
2024-02-09 10:50:52,713 - kedro.io.data_catalog - INFO - Loading data from 'test_logger_3_betula' (MemoryDataset)...
2024-02-09 10:50:52,764 - kedro.pipeline.node - INFO - Running node: normalise_data_node: normalise_data([train_logger_3_betula,val_logger_3_betula,test_logger_3_betula]) -> [train_logger_3_betula_norm,val_logger_3_betula_norm,test_logger_3_betula_norm]
2024-02-09 10:50:52,839 - kedro.io.data_catalog - INFO - Saving data to 'train_logger_3_betula_norm' (MemoryDataset)...
2024-02-09 10:50:52,855 - kedro.io.data_catalog - INFO - Saving data to 'val_logger_3_betula_norm' (MemoryDataset)...
2024-02-09 10:50:52,861 - kedro.io.data_catalog - INFO - Saving data to 'test_logger_3_betula_norm' (MemoryDataset)...
2024-02-09 10:50:52,877 - kedro.runner.sequential_runner - INFO - Completed 4 out of 9 tasks
2024-02-09 10:50:52,877 - kedro.io.data_catalog - INFO - Loading data from 'test_logger_3_betula_norm' (MemoryDataset)...
2024-02-09 10:50:52,896 - kedro.pipeline.node - INFO - Running node: windowing_test_node: get_windowed_data([test_logger_3_betula_norm]) -> [X_test,Y_test]
2024-02-09 10:50:55,811 - kedro.io.data_catalog - INFO - Saving data to 'X_test' (MemoryDataset)...
2024-02-09 10:50:55,817 - kedro.io.data_catalog - INFO - Saving data to 'Y_test' (MemoryDataset)...
2024-02-09 10:50:55,821 - kedro.runner.sequential_runner - INFO - Completed 5 out of 9 tasks
2024-02-09 10:50:55,824 - kedro.io.data_catalog - INFO - Loading data from 'train_logger_3_betula_norm' (MemoryDataset)...
2024-02-09 10:50:55,845 - kedro.pipeline.node - INFO - Running node: windowing_train_node: get_windowed_data([train_logger_3_betula_norm]) -> [X_train,Y_train]
2024-02-09 10:51:15,439 - kedro.io.data_catalog - INFO - Saving data to 'X_train' (MemoryDataset)...
2024-02-09 10:51:15,456 - kedro.io.data_catalog - INFO - Saving data to 'Y_train' (MemoryDataset)...
2024-02-09 10:51:15,473 - kedro.runner.sequential_runner - INFO - Completed 6 out of 9 tasks
2024-02-09 10:51:15,473 - kedro.io.data_catalog - INFO - Loading data from 'val_logger_3_betula_norm' (MemoryDataset)...
2024-02-09 10:51:15,506 - kedro.pipeline.node - INFO - Running node: windowing_val_node: get_windowed_data([val_logger_3_betula_norm]) -> [X_val,Y_val]
2024-02-09 10:51:20,900 - kedro.io.data_catalog - INFO - Saving data to 'X_val' (MemoryDataset)...
2024-02-09 10:51:20,916 - kedro.io.data_catalog - INFO - Saving data to 'Y_val' (MemoryDataset)...
2024-02-09 10:51:20,926 - kedro.runner.sequential_runner - INFO - Completed 7 out of 9 tasks
2024-02-09 10:51:20,929 - kedro.io.data_catalog - INFO - Loading data from 'X_test' (MemoryDataset)...
2024-02-09 10:51:20,935 - kedro.io.data_catalog - INFO - Loading data from 'Y_test' (MemoryDataset)...
2024-02-09 10:51:20,940 - kedro.pipeline.node - INFO - Running node: eval_node: evaluate_model([X_test,Y_test]) -> [evaluation]
2024-02-09 10:51:20,944 - kedro.pipeline.node - ERROR - Node 'eval_node: evaluate_model([X_test,Y_test]) -> [evaluation]' failed with error: 
No file or directory found at data/06_models/tensorflow_lstm_trained
2024-02-09 10:51:20,952 - kedro.runner.sequential_runner - WARNING - There are 2 nodes that have not run.
You can resume the pipeline run from the nearest nodes with persisted inputs by adding the following argument to your previous command:
  --from-nodes "data_cleaning_node,define_model_node"
2024-02-09 10:52:26,590 - kedro.framework.session.session - INFO - Kedro project tentative_agri_proj
2024-02-09 10:52:32,494 - tensorflow - WARNING - From C:\Users\paolo\Documents\GitHub\tentative_agri_proj\.venv\Lib\site-packages\keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

2024-02-09 10:52:32,917 - kedro.io.data_catalog - INFO - Loading data from 'logger_3_betula' (CSVDataSet)...
2024-02-09 10:52:33,127 - kedro.pipeline.node - INFO - Running node: data_cleaning_node: data_cleaning([logger_3_betula]) -> [logger_3_betula_cleaned]
2024-02-09 10:52:33,254 - kedro.io.data_catalog - INFO - Saving data to 'logger_3_betula_cleaned' (MemoryDataset)...
2024-02-09 10:52:33,268 - kedro.runner.sequential_runner - INFO - Completed 1 out of 9 tasks
2024-02-09 10:52:33,271 - kedro.pipeline.node - INFO - Running node: define_model_node: define_model(None) -> [model]
2024-02-09 10:52:33,418 - tensorflow - WARNING - From C:\Users\paolo\Documents\GitHub\tentative_agri_proj\.venv\Lib\site-packages\keras\src\backend.py:873: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

2024-02-09 10:52:37,179 - kedro.io.data_catalog - INFO - Saving data to 'model' (MemoryDataset)...
2024-02-09 10:52:37,179 - kedro.runner.sequential_runner - INFO - Completed 2 out of 9 tasks
2024-02-09 10:52:37,179 - kedro.io.data_catalog - INFO - Loading data from 'logger_3_betula_cleaned' (MemoryDataset)...
2024-02-09 10:52:37,214 - kedro.pipeline.node - INFO - Running node: split_data_node: split_data([logger_3_betula_cleaned]) -> [train_logger_3_betula,val_logger_3_betula,test_logger_3_betula]
2024-02-09 10:52:37,265 - kedro.io.data_catalog - INFO - Saving data to 'train_logger_3_betula' (MemoryDataset)...
2024-02-09 10:52:37,281 - kedro.io.data_catalog - INFO - Saving data to 'val_logger_3_betula' (MemoryDataset)...
2024-02-09 10:52:37,314 - kedro.io.data_catalog - INFO - Saving data to 'test_logger_3_betula' (MemoryDataset)...
2024-02-09 10:52:37,314 - kedro.runner.sequential_runner - INFO - Completed 3 out of 9 tasks
2024-02-09 10:52:37,331 - kedro.io.data_catalog - INFO - Loading data from 'train_logger_3_betula' (MemoryDataset)...
2024-02-09 10:52:37,346 - kedro.io.data_catalog - INFO - Loading data from 'val_logger_3_betula' (MemoryDataset)...
2024-02-09 10:52:37,349 - kedro.io.data_catalog - INFO - Loading data from 'test_logger_3_betula' (MemoryDataset)...
2024-02-09 10:52:37,399 - kedro.pipeline.node - INFO - Running node: normalise_data_node: normalise_data([train_logger_3_betula,val_logger_3_betula,test_logger_3_betula]) -> [train_logger_3_betula_norm,val_logger_3_betula_norm,test_logger_3_betula_norm]
2024-02-09 10:52:37,476 - kedro.io.data_catalog - INFO - Saving data to 'train_logger_3_betula_norm' (MemoryDataset)...
2024-02-09 10:52:37,493 - kedro.io.data_catalog - INFO - Saving data to 'val_logger_3_betula_norm' (MemoryDataset)...
2024-02-09 10:52:37,512 - kedro.io.data_catalog - INFO - Saving data to 'test_logger_3_betula_norm' (MemoryDataset)...
2024-02-09 10:52:37,513 - kedro.runner.sequential_runner - INFO - Completed 4 out of 9 tasks
2024-02-09 10:52:37,513 - kedro.io.data_catalog - INFO - Loading data from 'test_logger_3_betula_norm' (MemoryDataset)...
2024-02-09 10:52:37,548 - kedro.pipeline.node - INFO - Running node: windowing_test_node: get_windowed_data([test_logger_3_betula_norm]) -> [X_test,Y_test]
2024-02-09 10:52:40,015 - kedro.io.data_catalog - INFO - Saving data to 'X_test' (MemoryDataset)...
2024-02-09 10:52:40,035 - kedro.io.data_catalog - INFO - Saving data to 'Y_test' (MemoryDataset)...
2024-02-09 10:52:40,039 - kedro.runner.sequential_runner - INFO - Completed 5 out of 9 tasks
2024-02-09 10:52:40,041 - kedro.io.data_catalog - INFO - Loading data from 'train_logger_3_betula_norm' (MemoryDataset)...
2024-02-09 10:52:40,062 - kedro.pipeline.node - INFO - Running node: windowing_train_node: get_windowed_data([train_logger_3_betula_norm]) -> [X_train,Y_train]
2024-02-09 10:52:57,122 - kedro.io.data_catalog - INFO - Saving data to 'X_train' (MemoryDataset)...
2024-02-09 10:52:57,122 - kedro.io.data_catalog - INFO - Saving data to 'Y_train' (MemoryDataset)...
2024-02-09 10:52:57,146 - kedro.runner.sequential_runner - INFO - Completed 6 out of 9 tasks
2024-02-09 10:52:57,146 - kedro.io.data_catalog - INFO - Loading data from 'val_logger_3_betula_norm' (MemoryDataset)...
2024-02-09 10:52:57,163 - kedro.pipeline.node - INFO - Running node: windowing_val_node: get_windowed_data([val_logger_3_betula_norm]) -> [X_val,Y_val]
2024-02-09 10:53:02,233 - kedro.io.data_catalog - INFO - Saving data to 'X_val' (MemoryDataset)...
2024-02-09 10:53:02,242 - kedro.io.data_catalog - INFO - Saving data to 'Y_val' (MemoryDataset)...
2024-02-09 10:53:02,248 - kedro.runner.sequential_runner - INFO - Completed 7 out of 9 tasks
2024-02-09 10:53:02,249 - kedro.io.data_catalog - INFO - Loading data from 'X_train' (MemoryDataset)...
2024-02-09 10:53:02,258 - kedro.io.data_catalog - INFO - Loading data from 'Y_train' (MemoryDataset)...
2024-02-09 10:53:02,275 - kedro.io.data_catalog - INFO - Loading data from 'X_val' (MemoryDataset)...
2024-02-09 10:53:02,275 - kedro.io.data_catalog - INFO - Loading data from 'Y_val' (MemoryDataset)...
2024-02-09 10:53:02,288 - kedro.io.data_catalog - INFO - Loading data from 'model' (MemoryDataset)...
2024-02-09 10:53:02,291 - kedro.pipeline.node - INFO - Running node: training_node: train_model([X_train,Y_train,X_val,Y_val,model]) -> [history]
2024-02-09 10:53:02,357 - tensorflow - WARNING - From C:\Users\paolo\Documents\GitHub\tentative_agri_proj\.venv\Lib\site-packages\keras\src\saving\legacy\saved_model\load.py:107: The name tf.gfile.Exists is deprecated. Please use tf.io.gfile.exists instead.

2024-02-09 10:53:04,100 - tensorflow - WARNING - From C:\Users\paolo\Documents\GitHub\tentative_agri_proj\.venv\Lib\site-packages\keras\src\utils\tf_utils.py:492: The name tf.ragged.RaggedTensorValue is deprecated. Please use tf.compat.v1.ragged.RaggedTensorValue instead.

2024-02-09 10:57:35,865 - kedro.pipeline.node - ERROR - Node 'training_node: train_model([X_train,Y_train,X_val,Y_val,model]) -> [history]' failed with error: 
Failed to save outputs of node training_node: train_model([X_train,Y_train,X_val,Y_val,model]) -> [history].
The node definition contains a list of outputs ['history'], whereas the node function returned a 'History'.
2024-02-09 10:57:35,883 - kedro.runner.sequential_runner - WARNING - There are 2 nodes that have not run.
You can resume the pipeline run from the nearest nodes with persisted inputs by adding the following argument to your previous command:
  --from-nodes "define_model_node,data_cleaning_node"
2024-02-09 10:58:03,996 - kedro.framework.session.session - INFO - Kedro project tentative_agri_proj
2024-02-09 10:58:09,191 - tensorflow - WARNING - From C:\Users\paolo\Documents\GitHub\tentative_agri_proj\.venv\Lib\site-packages\keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

2024-02-09 10:58:09,646 - kedro.io.data_catalog - INFO - Loading data from 'logger_3_betula' (CSVDataSet)...
2024-02-09 10:58:09,992 - kedro.pipeline.node - INFO - Running node: data_cleaning_node: data_cleaning([logger_3_betula]) -> [logger_3_betula_cleaned]
2024-02-09 10:58:10,148 - kedro.io.data_catalog - INFO - Saving data to 'logger_3_betula_cleaned' (MemoryDataset)...
2024-02-09 10:58:10,163 - kedro.runner.sequential_runner - INFO - Completed 1 out of 9 tasks
2024-02-09 10:58:10,163 - kedro.pipeline.node - INFO - Running node: define_model_node: define_model(None) -> [model]
2024-02-09 10:58:10,345 - tensorflow - WARNING - From C:\Users\paolo\Documents\GitHub\tentative_agri_proj\.venv\Lib\site-packages\keras\src\backend.py:873: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

2024-02-09 10:58:15,076 - kedro.io.data_catalog - INFO - Saving data to 'model' (MemoryDataset)...
2024-02-09 10:58:15,080 - kedro.runner.sequential_runner - INFO - Completed 2 out of 9 tasks
2024-02-09 10:58:15,083 - kedro.io.data_catalog - INFO - Loading data from 'logger_3_betula_cleaned' (MemoryDataset)...
2024-02-09 10:58:15,098 - kedro.pipeline.node - INFO - Running node: split_data_node: split_data([logger_3_betula_cleaned]) -> [train_logger_3_betula,val_logger_3_betula,test_logger_3_betula]
2024-02-09 10:58:15,163 - kedro.io.data_catalog - INFO - Saving data to 'train_logger_3_betula' (MemoryDataset)...
2024-02-09 10:58:15,182 - kedro.io.data_catalog - INFO - Saving data to 'val_logger_3_betula' (MemoryDataset)...
2024-02-09 10:58:15,197 - kedro.io.data_catalog - INFO - Saving data to 'test_logger_3_betula' (MemoryDataset)...
2024-02-09 10:58:15,215 - kedro.runner.sequential_runner - INFO - Completed 3 out of 9 tasks
2024-02-09 10:58:15,227 - kedro.io.data_catalog - INFO - Loading data from 'train_logger_3_betula' (MemoryDataset)...
2024-02-09 10:58:15,244 - kedro.io.data_catalog - INFO - Loading data from 'val_logger_3_betula' (MemoryDataset)...
2024-02-09 10:58:15,261 - kedro.io.data_catalog - INFO - Loading data from 'test_logger_3_betula' (MemoryDataset)...
2024-02-09 10:58:15,299 - kedro.pipeline.node - INFO - Running node: normalise_data_node: normalise_data([train_logger_3_betula,val_logger_3_betula,test_logger_3_betula]) -> [train_logger_3_betula_norm,val_logger_3_betula_norm,test_logger_3_betula_norm]
2024-02-09 10:58:15,385 - kedro.io.data_catalog - INFO - Saving data to 'train_logger_3_betula_norm' (MemoryDataset)...
2024-02-09 10:58:15,404 - kedro.io.data_catalog - INFO - Saving data to 'val_logger_3_betula_norm' (MemoryDataset)...
2024-02-09 10:58:15,416 - kedro.io.data_catalog - INFO - Saving data to 'test_logger_3_betula_norm' (MemoryDataset)...
2024-02-09 10:58:15,433 - kedro.runner.sequential_runner - INFO - Completed 4 out of 9 tasks
2024-02-09 10:58:15,433 - kedro.io.data_catalog - INFO - Loading data from 'test_logger_3_betula_norm' (MemoryDataset)...
2024-02-09 10:58:15,465 - kedro.pipeline.node - INFO - Running node: windowing_test_node: get_windowed_data([test_logger_3_betula_norm]) -> [X_test,Y_test]
2024-02-09 10:58:18,459 - kedro.io.data_catalog - INFO - Saving data to 'X_test' (MemoryDataset)...
2024-02-09 10:58:18,475 - kedro.io.data_catalog - INFO - Saving data to 'Y_test' (MemoryDataset)...
2024-02-09 10:58:18,475 - kedro.runner.sequential_runner - INFO - Completed 5 out of 9 tasks
2024-02-09 10:58:18,475 - kedro.io.data_catalog - INFO - Loading data from 'train_logger_3_betula_norm' (MemoryDataset)...
2024-02-09 10:58:18,510 - kedro.pipeline.node - INFO - Running node: windowing_train_node: get_windowed_data([train_logger_3_betula_norm]) -> [X_train,Y_train]
2024-02-09 10:58:39,686 - kedro.io.data_catalog - INFO - Saving data to 'X_train' (MemoryDataset)...
2024-02-09 10:58:39,706 - kedro.io.data_catalog - INFO - Saving data to 'Y_train' (MemoryDataset)...
2024-02-09 10:58:39,723 - kedro.runner.sequential_runner - INFO - Completed 6 out of 9 tasks
2024-02-09 10:58:39,740 - kedro.io.data_catalog - INFO - Loading data from 'val_logger_3_betula_norm' (MemoryDataset)...
2024-02-09 10:58:39,797 - kedro.pipeline.node - INFO - Running node: windowing_val_node: get_windowed_data([val_logger_3_betula_norm]) -> [X_val,Y_val]
2024-02-09 10:58:45,239 - kedro.io.data_catalog - INFO - Saving data to 'X_val' (MemoryDataset)...
2024-02-09 10:58:45,239 - kedro.io.data_catalog - INFO - Saving data to 'Y_val' (MemoryDataset)...
2024-02-09 10:58:45,255 - kedro.runner.sequential_runner - INFO - Completed 7 out of 9 tasks
2024-02-09 10:58:45,257 - kedro.io.data_catalog - INFO - Loading data from 'X_train' (MemoryDataset)...
2024-02-09 10:58:45,271 - kedro.io.data_catalog - INFO - Loading data from 'Y_train' (MemoryDataset)...
2024-02-09 10:58:45,271 - kedro.io.data_catalog - INFO - Loading data from 'X_val' (MemoryDataset)...
2024-02-09 10:58:45,288 - kedro.io.data_catalog - INFO - Loading data from 'Y_val' (MemoryDataset)...
2024-02-09 10:58:45,288 - kedro.io.data_catalog - INFO - Loading data from 'model' (MemoryDataset)...
2024-02-09 10:58:45,303 - kedro.pipeline.node - INFO - Running node: training_node: train_model([X_train,Y_train,X_val,Y_val,model]) -> [history]
2024-02-09 10:58:45,368 - tensorflow - WARNING - From C:\Users\paolo\Documents\GitHub\tentative_agri_proj\.venv\Lib\site-packages\keras\src\saving\legacy\saved_model\load.py:107: The name tf.gfile.Exists is deprecated. Please use tf.io.gfile.exists instead.

2024-02-09 10:58:47,645 - tensorflow - WARNING - From C:\Users\paolo\Documents\GitHub\tentative_agri_proj\.venv\Lib\site-packages\keras\src\utils\tf_utils.py:492: The name tf.ragged.RaggedTensorValue is deprecated. Please use tf.compat.v1.ragged.RaggedTensorValue instead.

2024-02-09 11:03:27,242 - kedro.io.data_catalog - INFO - Saving data to 'history' (MemoryDataset)...
2024-02-09 11:03:27,727 - kedro.runner.sequential_runner - INFO - Completed 8 out of 9 tasks
2024-02-09 11:03:27,727 - kedro.io.data_catalog - INFO - Loading data from 'X_test' (MemoryDataset)...
2024-02-09 11:03:27,742 - kedro.io.data_catalog - INFO - Loading data from 'Y_test' (MemoryDataset)...
2024-02-09 11:03:27,748 - kedro.io.data_catalog - INFO - Loading data from 'history' (MemoryDataset)...
2024-02-09 11:03:28,136 - kedro.pipeline.node - INFO - Running node: eval_node: evaluate_model([X_test,Y_test,history]) -> [evaluation]
2024-02-09 11:03:31,432 - kedro.io.data_catalog - INFO - Saving data to 'evaluation' (MemoryDataset)...
2024-02-09 11:03:31,432 - kedro.runner.sequential_runner - INFO - Completed 9 out of 9 tasks
2024-02-09 11:03:31,451 - kedro.runner.sequential_runner - INFO - Pipeline execution completed successfully.
2024-02-09 11:03:31,454 - kedro.io.data_catalog - INFO - Loading data from 'evaluation' (MemoryDataset)...
